## Import Libraries

In [1]:
# %pip install -r requirements.txt
import numpy as np
import pandas as pd

### Step 1: Define Parameters

#### Dates

In [2]:
from datetime import datetime, timedelta
from pandas.tseries.offsets import BDay

# Time Range
end_date = (datetime.today() - BDay(1)).to_pydatetime()  # Subtract 1 business day
start_date = end_date - timedelta(days=5*365)

#### Risk-free rate (T-bill, %)

In [3]:
def load_and_filter_data(file_path, tickers, start_date, end_date):
    df = pd.read_csv(file_path)

    # Filter columns to available tickers
    available_tickers = [ticker for ticker in tickers if ticker in df.columns]
    print(f"Found {len(available_tickers)} of {len(tickers)} tickers in {file_path}")
    print(f"Missing tickers: {[ticker for ticker in tickers if ticker not in df.columns]}")

    columns_to_keep = ['Date'] + available_tickers if 'Date' in df.columns else available_tickers
    df = df[columns_to_keep] if all(col in df.columns for col in columns_to_keep) else df

    # Handle Date column or index
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
        df = df.set_index('Date')
    else:
        df.index = pd.to_datetime(df.index)
        df = df.loc[start_date:end_date]

    return df.sort_index(axis=0).sort_index(axis=1)

# Load and process data
daily_risk_free_df = load_and_filter_data('data/datasets/daily_treasury_rates.csv', ['^IRX'], start_date, end_date)
# risk_free_rate = .0433 
risk_free_rate = daily_risk_free_df.iloc[-1, 0] / 100

# Display result
print("Risk-Free Rate:", risk_free_rate, "-- 13 WEEK TREASURY BILL (^IRX)")
daily_risk_free_df.head()

Found 1 of 1 tickers in data/datasets/daily_treasury_rates.csv
Missing tickers: []
Risk-Free Rate: 0.042800000000000005 -- 13 WEEK TREASURY BILL (^IRX)

             ^IRX
Date
2020-05-14  0.105
2020-05-15  0.103
2020-05-18  0.105
2020-05-19  0.118
2020-05-20  0.118

### Step 2: Import Bond Data

In [4]:
blackrock_etf_df = pd.read_csv('data/datasets/fundamentals_blackrock_bonds.csv')
blackrock_etf_df.head()

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,AGG,iShares Core U.S. Aggregate Bond ETF,3.16,8.00,1.96,-0.68,1.50,3.10,"Apr 30, 2025","Sep 22, 2003",122536836066,239458,https://www.blackrock.com/us/individual/produc...,0.0481,8.16,0.53,0.0354
1,AGIH,iShares Inflation Hedged U.S. Aggregate Bond ETF,3.42,7.17,-,-,-,2.72,"Apr 30, 2025","Jun 22, 2022",2450541,328179,https://www.blackrock.com/us/individual/produc...,0.0475,7.78,0.50,NaN
2,AGRH,iShares Interest Rate Hedged U.S. Aggregate Bo...,0.77,4.50,-,-,-,5.19,"Apr 30, 2025","Jun 22, 2022",7745146,328180,https://www.blackrock.com/us/individual/produc...,0.0529,8.16,-0.15,NaN
3,AGZ,iShares Agency Bond ETF,2.85,6.98,2.84,0.48,1.74,2.34,"Apr 30, 2025","Nov 05, 2008",607565592,239457,https://www.blackrock.com/us/individual/produc...,0.0432,4.13,0.24,0.0346
4,BAIPX,iShares Short-Term TIPS Bond Index Fund,3.76,7.54,3.19,3.67,-,2.83,"Apr 30, 2025","Feb 16, 2016",5260980,282302,https://www.blackrock.com/us/individual/produc...,NaN,NaN,NaN,NaN

### Step 3: Filter for Convexity > 1

In [5]:
bond_funds_filtered_df = blackrock_etf_df[blackrock_etf_df['Convexity'] >= 1].sort_values(by='Convexity', ascending=False).reset_index(drop=True)

# Define all possible percentage columns
all_percentage_cols = ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)', 'Since Inception (%)']

# Filter to only include columns that actually exist in the DataFrame
percentage_cols = [col for col in all_percentage_cols if col in bond_funds_filtered_df.columns]

print(f"Processing the following percentage columns: {percentage_cols}")

# First, ensure all percentage columns are converted to numeric values
for col in percentage_cols:
    # Convert to numeric first, handling errors by setting them to NaN
    bond_funds_filtered_df[col] = pd.to_numeric(bond_funds_filtered_df[col], errors='coerce')

# Now perform the division safely
for col in percentage_cols:
    bond_funds_filtered_df[col] = bond_funds_filtered_df[col] / 100

# Format as percentage strings
for col in percentage_cols + ['Yield_To_Maturity', 'Weighted_Avg_Coupon']:
    # Check if column exists and only process if it does
    if col in bond_funds_filtered_df.columns:
        # Only format cells that aren't NaN
        bond_funds_filtered_df[col] = bond_funds_filtered_df[col].apply(
            lambda x: '{:.2%}'.format(x) if pd.notna(x) else x
        )

bond_tickers = bond_funds_filtered_df['Ticker'].tolist()

# Display Outputs
print(f"Number of iShares bond/fixed income funds with Convexity >= 1: {len(bond_tickers)}")
print(bond_tickers)
display(bond_funds_filtered_df.head())

Processing the following percentage columns: ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)']
Number of iShares bond/fixed income funds with Convexity >= 1: 13
['GOVZ', 'IBGL', 'TLT', 'ILTB', 'IBGB', 'IGLB', 'IBGA', 'TLH', 'ICVT', 'LQD', 'IGOV', 'ELQD', 'LQDI']

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,0.65%,1.05%,-12.71%,NaN,NaN,-15.79%,"Apr 30, 2025","Sep 22, 2020",248788662,315911,https://www.blackrock.com/us/individual/produc...,5.00%,27.31,7.25,0.00%
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Apr 30, 2025","Mar 25, 2025",3611966,342146,https://www.blackrock.com/us/individual/produc...,4.91%,29.75,3.49,4.63%
2,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",46739132001,239454,https://www.blackrock.com/us/individual/produc...,4.98%,25.72,3.39,2.86%
3,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",597023945,239424,https://www.blackrock.com/us/individual/produc...,5.68%,21.92,2.35,3.95%
4,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Apr 30, 2025","Mar 25, 2025",3633184,342124,https://www.blackrock.com/us/individual/produc...,4.98%,19.96,2.35,3.18%

In [6]:
# Ensure relevant columns are numeric
bond_funds_filtered_df['Yield_To_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Yield_To_Maturity'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Coupon'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Coupon'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Maturity'], errors='coerce'
)

# Fill missing values with 0
bond_funds_filtered_df = bond_funds_filtered_df.fillna(0)

# Divide the columns by 100 and reassign
bond_funds_filtered_df['Yield_To_Maturity'] = bond_funds_filtered_df['Yield_To_Maturity'] / 100
bond_funds_filtered_df['Weighted_Avg_Coupon'] = bond_funds_filtered_df['Weighted_Avg_Coupon'] / 100

# Display the DataFrame with the updated columns
display(bond_funds_filtered_df.head())

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,0.65%,1.05%,-12.71%,0,0,-15.79%,"Apr 30, 2025","Sep 22, 2020",248788662,315911,https://www.blackrock.com/us/individual/produc...,0.0500,27.31,7.25,0.0000
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,0,0,0,0,0,0,"Apr 30, 2025","Mar 25, 2025",3611966,342146,https://www.blackrock.com/us/individual/produc...,0.0491,29.75,3.49,0.0463
2,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",46739132001,239454,https://www.blackrock.com/us/individual/produc...,0.0498,25.72,3.39,0.0286
3,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",597023945,239424,https://www.blackrock.com/us/individual/produc...,0.0568,21.92,2.35,0.0395
4,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,0,0,0,0,0,0,"Apr 30, 2025","Mar 25, 2025",3633184,342124,https://www.blackrock.com/us/individual/produc...,0.0498,19.96,2.35,0.0318

### Step 4: Import Quotes

In [7]:
bond_tickers = bond_funds_filtered_df['Ticker'].tolist()

In [8]:
def load_and_filter_data(file_path, tickers, start_date, end_date):
    df = pd.read_csv(file_path)

    # Filter columns to available tickers
    available_tickers = [ticker for ticker in tickers if ticker in df.columns]
    print(f"Found {len(available_tickers)} of {len(tickers)} tickers in {file_path}")
    print(f"Missing tickers: {[ticker for ticker in tickers if ticker not in df.columns]}")

    columns_to_keep = ['Date'] + available_tickers if 'Date' in df.columns else available_tickers
    df = df[columns_to_keep] if all(col in df.columns for col in columns_to_keep) else df

    # Handle Date column or index
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
        df = df.set_index('Date')
    else:
        df.index = pd.to_datetime(df.index)
        df = df.loc[start_date:end_date]

    return df.sort_index(axis=0).sort_index(axis=1)

# Load and process data
bonds_daily_df = load_and_filter_data('data/datasets/daily_bond_quotes.csv', bond_tickers, start_date, end_date)

bonds_monthly_prices = (bonds_daily_df.set_index(pd.to_datetime(bonds_daily_df.pop('Date')))
      if 'Date' in bonds_daily_df.columns else bonds_daily_df.copy())
bonds_monthly_prices.index = pd.to_datetime(bonds_monthly_prices.index)              
bonds_monthly_prices = (bonds_monthly_prices.resample('MS').last()
   .reset_index()
   .rename(columns={'index': 'Date'}))

display(bonds_daily_df.head())

Found 10 of 13 tickers in data/datasets/daily_bond_quotes.csv
Missing tickers: ['IBGL', 'IBGB', 'IBGA']

,ELQD,GOVZ,ICVT,IGLB,IGOV,ILTB,LQD,LQDI,TLH,TLT
Date,,,,,,,,,,
2020-05-14,NaN,NaN,52.32,53.59,48.84,59.71,108.30,21.04,145.45,145.89
2020-05-15,NaN,NaN,52.47,53.73,48.92,59.64,108.68,20.98,145.07,145.51
2020-05-18,NaN,NaN,53.14,53.90,49.03,59.37,109.30,21.06,143.08,142.32
2020-05-19,NaN,NaN,53.32,53.90,49.12,59.44,109.38,21.43,143.59,142.85
2020-05-20,NaN,NaN,54.00,54.77,49.37,60.18,110.59,21.54,143.83,143.28

### Step 5: Prepare Data (Drop Invalid Tickers)

In [9]:
# Identify columns with null values in first or last 50 rows
first_50_nulls = bonds_daily_df.head(50).isnull().any()
last_50_nulls = bonds_daily_df.tail(50).isnull().any()

# Columns to drop are those with nulls in first 50 OR last 50 rows
columns_to_drop = first_50_nulls | last_50_nulls
bad_columns = columns_to_drop[columns_to_drop].index.tolist()

print(f"Dropping {len(bad_columns)} columns with missing values in first/last 50 records: {bad_columns}")

# Drop those columns
bonds_daily_filtered_df = bonds_daily_df.loc[:, ~columns_to_drop]

# Display the first few rows of the cleaned dataframe
bonds_daily_filtered_df.head()

Dropping 2 columns with missing values in first/last 50 records: ['ELQD', 'GOVZ']

             ICVT   IGLB   IGOV   ILTB     LQD   LQDI     TLH     TLT
Date
2020-05-14  52.32  53.59  48.84  59.71  108.30  21.04  145.45  145.89
2020-05-15  52.47  53.73  48.92  59.64  108.68  20.98  145.07  145.51
2020-05-18  53.14  53.90  49.03  59.37  109.30  21.06  143.08  142.32
2020-05-19  53.32  53.90  49.12  59.44  109.38  21.43  143.59  142.85
2020-05-20  54.00  54.77  49.37  60.18  110.59  21.54  143.83  143.28

### Step 6: Calculate Returns (Lognormal)

In [10]:
log_returns_df = np.log(bonds_daily_filtered_df / bonds_daily_filtered_df.shift(1))
log_returns_df = log_returns_df.dropna().sort_index(axis=0, ascending=True).sort_index(axis=1, ascending=True)
log_returns_df.head()

,ICVT,IGLB,IGOV,ILTB,LQD,LQDI,TLH,TLT
Date,,,,,,,,
2020-05-15,0.002863,0.002609,0.001637,-0.001173,0.003503,-0.002856,-0.002616,-0.002608
2020-05-18,0.012688,0.003159,0.002246,-0.004537,0.005689,0.003806,-0.013812,-0.022167
2020-05-19,0.003382,0.000000,0.001834,0.001178,0.000732,0.017416,0.003558,0.003717
2020-05-20,0.012673,0.016012,0.005077,0.012373,0.011002,0.005120,0.001670,0.003006
2020-05-21,-0.003153,-0.001645,0.000203,0.000332,-0.000814,0.006017,0.002222,0.002509

### Step 7: Calculate Modified Duration (D*)

In [11]:
def calculate_modified_duration(settlement_date, maturity_date, coupon_rate, ytm, frequency):
    total_years = (maturity_date - settlement_date).days / 365
    num_periods = int(total_years * frequency)
    face_value, coupon_payment = 100, coupon_rate * 100 / frequency
    cash_flows = np.full(num_periods, coupon_payment)
    cash_flows[-1] += face_value
    times = np.arange(1, num_periods + 1) / frequency
    discounted_cash_flows = cash_flows / (1 + ytm / frequency) ** times
    macaulay_duration = (times * discounted_cash_flows).sum() / discounted_cash_flows.sum()
    return macaulay_duration / (1 + ytm / frequency)

def calculate_duration_for_bonds(df):
    df['Duration (D*)'] = df.apply(lambda row: calculate_modified_duration(
        end_date,
        end_date + timedelta(days=int(row['Weighted_Avg_Maturity'] * 365)),
        row['Weighted_Avg_Coupon'], row['Yield_To_Maturity'], 2
    ) if pd.notna(row['Yield_To_Maturity']) and pd.notna(row['Weighted_Avg_Coupon']) and pd.notna(row['Weighted_Avg_Maturity']) else np.nan, axis=1)
    return df.round(3)

bond_tickers = bonds_daily_filtered_df.columns.tolist()
bond_funds_filtered_df = bond_funds_filtered_df[bond_funds_filtered_df['Ticker'].isin(bond_tickers)].reset_index(drop=True)

# Apply the function to your DataFrame
bond_funds_duration_df = calculate_duration_for_bonds(bond_funds_filtered_df)

# Display the updated DataFrame
print(bond_tickers)
bond_funds_duration_df[['Ticker', 'Weighted_Avg_Maturity', 'Weighted_Avg_Coupon', 'Yield_To_Maturity', 'Duration (D*)', 'Convexity']]

['ICVT', 'IGLB', 'IGOV', 'ILTB', 'LQD', 'LQDI', 'TLH', 'TLT']

,Ticker,Weighted_Avg_Maturity,Weighted_Avg_Coupon,Yield_To_Maturity,Duration (D*),Convexity
0,TLT,25.72,0.029,0.050,18.109,3.39
1,ILTB,21.92,0.040,0.057,14.871,2.35
2,IGLB,22.17,0.046,0.060,14.570,2.17
3,TLH,17.11,0.032,0.049,13.173,1.88
4,ICVT,2.92,0.021,0.030,2.412,1.21
5,LQD,12.90,0.044,0.055,9.736,1.11
6,IGOV,9.58,0.022,0.029,8.529,1.11
7,LQDI,12.45,0.000,0.053,11.690,1.06

### Step 8: Calculate Price Sensitivity with Convexity (Changes in YTM)

In [ ]:
def calculate_price_change_sensitivity(df, rate_change=-0.01):
    """
    Calculate Price Change Sensitivity (Expected Return) using Duration (D*) and Convexity.
    
    Parameters:
    - df: DataFrame containing 'Duration (D*)' and 'Convexity' columns.
    - rate_change: Change in interest rates (default is -1% or -0.01).
    
    Returns:
    - Updated DataFrame with 'Price Change Sensitivity (Expected Return)' column.
    """
    df['Price Change Sensitivity (Expected Return)'] = df.apply(
        lambda row: row['Duration (D*)'] + 0.5 * row['Convexity'] * (rate_change ** 2)
        if pd.notna(row['Duration (D*)']) and pd.notna(row['Convexity']) else np.nan,
        axis=1
    ) / 100
    return df.round(4)

# Apply the function to your DataFrame
bond_funds_sensitivity_df = calculate_price_change_sensitivity(bond_funds_duration_df)
bond_funds_sensitivity_df[['Ticker', 'Duration (D*)', 'Convexity', 'Price Change Sensitivity (Expected Return)']]

  Ticker  Duration (D*)  Convexity  Price Change Sensitivity
0    TLT         18.109       3.39                    0.1811
1   ILTB         14.871       2.35                    0.1487
2   IGLB         14.570       2.17                    0.1457
3    TLH         13.173       1.88                    0.1317
4   ICVT          2.412       1.21                    0.0241
5    LQD          9.736       1.11                    0.0974
6   IGOV          8.529       1.11                    0.0853
7   LQDI         11.690       1.06                    0.1169

### Step 9: Select the Best Bond (Highest Price Change Sensitivity (Expected Return))

In [ ]:
# Find the row index where Price Change Sensitivity (Expected Return) is at its maximum
best_bond_ticker = bond_funds_sensitivity_df["Price Change Sensitivity (Expected Return)"].idxmax()

# Get the maximum value for display
max_sensitivity = bond_funds_sensitivity_df["Price Change Sensitivity (Expected Return)"].max()

print(f"Best Bond Ticker: {best_bond_ticker}")
print(f"Maximum Price Change Sensitivity (Expected Return): {max_sensitivity:.6f}")
bond_funds_sensitivity_df.loc[best_bond_ticker]

Best Bond Ticker: 0
Maximum Price Change Sensitivity: 0.181100

Ticker                                                                    TLT
Name                                       iShares 20+ Year Treasury Bond ETF
YTD (%)                                                                 3.23%
1Y (%)                                                                  5.46%
3Y (%)                                                                 -6.03%
5Y (%)                                                                 -9.43%
10Y (%)                                                                -0.87%
Incept (%)                                                              3.79%
Perf. as of                                                      Apr 30, 2025
Inception Date                                                   Jul 22, 2002
Net Assets                                                        46739132001
Product_ID                                                             239454
URL                         https://www.blackrock.com/us/individual/produc...
Yield_To_Maturity                                                        0.05
Weighted_Avg_Maturity                                                   25.72
Convexity                                                                3.39
Weighted_Avg_Coupon                                                     0.029
Duration (D*)                                                          18.109
Price Change Sensitivity                                               0.1811
Name: 0, dtype: object

### Step 10: Add Returns and Standard Deviation to DataFrame

In [14]:
# Step 1: Unpivot (melt) the log_returns_df
log_returns_long = log_returns_df.reset_index().melt(id_vars='Date', var_name='Ticker', value_name='Log Return')

# Step 2: Ensure 'Log Return' column is numeric
log_returns_long['Log Return'] = pd.to_numeric(log_returns_long['Log Return'], errors='coerce')

# Step 3: Drop rows with NaN values in 'Log Return'
log_returns_long = log_returns_long.dropna(subset=['Log Return'])

# Step 4: Calculate statistics for each ticker
log_returns_stats = log_returns_long.groupby('Ticker').agg(
    Expected_Return=('Log Return', lambda x: ((1 + x).prod() ** (252 / len(x))) - 1),  # Geometric mean (annualized return)
    Standard_Deviation=('Log Return', lambda x: x.std() * np.sqrt(252))  # Annualized standard deviation
).reset_index()

# Step 5: Calculate Sharpe Ratio
log_returns_stats['Sharpe_Ratio'] = (log_returns_stats['Expected_Return'] - risk_free_rate) / log_returns_stats['Standard_Deviation']

# Step 6: Set Index
log_returns_stats.set_index('Ticker', inplace=True)

# Step 7: Merge with bond_funds_sensitivity_df
bond_funds_sensitivity_df = bond_funds_sensitivity_df.merge(
    log_returns_stats,
    on='Ticker',
    how='left'
)

# Display the updated DataFrame
display(bond_funds_sensitivity_df)

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,...,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon,Duration (D*),Price Change Sensitivity,Expected_Return,Standard_Deviation,Sharpe_Ratio
0,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",...,https://www.blackrock.com/us/individual/produc...,0.050,25.72,3.39,0.029,18.109,0.1811,-0.112092,0.162590,-0.952655
1,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",...,https://www.blackrock.com/us/individual/produc...,0.057,21.92,2.35,0.040,14.871,0.1487,-0.050739,0.128063,-0.730417
2,IGLB,iShares 10+ Year Investment Grade Corporate Bo...,1.10%,6.19%,0.87%,-1.95%,2.09%,4.27%,"Apr 30, 2025","Dec 08, 2009",...,https://www.blackrock.com/us/individual/produc...,0.060,22.17,2.17,0.046,14.570,0.1457,-0.027785,0.126813,-0.556608
3,TLH,iShares 10-20 Year Treasury Bond ETF,4.02%,7.73%,-2.63%,-6.71%,-0.35%,2.95%,"Apr 30, 2025","Jan 05, 2007",...,https://www.blackrock.com/us/individual/produc...,0.049,17.11,1.88,0.032,13.173,0.1317,-0.081352,0.128706,-0.964615
4,ICVT,iShares Convertible Bond ETF,0.45%,13.09%,5.30%,10.75%,0,9.08%,"Apr 30, 2025","Jun 02, 2015",...,https://www.blackrock.com/us/individual/produc...,0.030,2.92,1.21,0.021,2.412,0.0241,0.095590,0.150636,0.350449
5,LQD,iShares iBoxx $ Investment Grade Corporate Bon...,2.22%,7.50%,2.61%,-0.17%,2.37%,4.41%,"Apr 30, 2025","Jul 22, 2002",...,https://www.blackrock.com/us/individual/produc...,0.055,12.90,1.11,0.044,9.736,0.0974,-0.007024,0.087784,-0.567574
6,IGOV,iShares International Treasury Bond ETF,8.65%,9.56%,-0.71%,-3.32%,-0.86%,0.21%,"Apr 30, 2025","Jan 21, 2009",...,https://www.blackrock.com/us/individual/produc...,0.029,9.58,1.11,0.022,8.529,0.0853,-0.041516,0.096206,-0.876414
7,LQDI,iShares Inflation Hedged Corporate Bond ETF,2.32%,6.38%,2.12%,4.01%,0,3.95%,"Apr 30, 2025","May 08, 2018",...,https://www.blackrock.com/us/individual/produc...,0.053,12.45,1.06,0.000,11.690,0.1169,0.036246,0.088271,-0.074248

### Step 11: Export Data to Excel

In [15]:
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font
import os

# Check if 'Ticker' is already the index or still a column
if 'Ticker' in bond_funds_sensitivity_df.columns:
    # Set 'Ticker' as index if it's still a column
    bond_funds_sensitivity_df.set_index('Ticker', inplace=True)
elif bond_funds_sensitivity_df.index.name != 'Ticker':
    # If it's neither a column nor the index name, print info for debugging
    print("Warning: 'Ticker' is not available as a column or index name.")
    print(f"Available columns: {bond_funds_sensitivity_df.columns.tolist()}")
    print(f"Current index name: {bond_funds_sensitivity_df.index.name}")

# Get the actual ticker symbol name for the best bond
if isinstance(best_bond_ticker, (int, np.integer)):
    best_bond_ticker_name = bond_funds_sensitivity_df.iloc[best_bond_ticker].name
    print(f"Converting best bond index {best_bond_ticker} to ticker name {best_bond_ticker_name}")
    best_bond_ticker = best_bond_ticker_name

# Write both DataFrames to Excel sheets
output_file = f'reports/portfolio-{datetime.date(end_date)}.xlsx'

# First export the bond_funds_sensitivity_df
with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    bond_funds_sensitivity_df.to_excel(
        writer, 
        sheet_name='bond', 
        index=True, 
        startrow=0, 
        startcol=0
    )

# For the daily_quotes data, we need to merge with existing data
if os.path.exists(output_file):
    try:
        # Try to read existing data from the daily_quotes sheet
        existing_daily_prices = pd.read_excel(output_file, sheet_name='daily_quotes', index_col=0)
        
        # Ensure the index (Date) is in the right format for merging
        if isinstance(bonds_daily_filtered_df.index, pd.DatetimeIndex):
            existing_daily_prices.index = pd.to_datetime(existing_daily_prices.index)
        
        # Make sure best_bond_ticker is a valid column in bonds_daily_filtered_df
        if best_bond_ticker not in bonds_daily_filtered_df.columns:
            print(f"Warning: {best_bond_ticker} not found in columns. Available columns: {bonds_daily_filtered_df.columns.tolist()}")
        else:
            # Merge the DataFrames based on the Date index
            merged_daily_prices = pd.concat([existing_daily_prices, bonds_daily_filtered_df[best_bond_ticker]], axis=1)
            # Remove duplicate columns if any
            merged_daily_prices = merged_daily_prices.loc[:,~merged_daily_prices.columns.duplicated()]
            
            # Write the merged data back to Excel
            with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
                merged_daily_prices.to_excel(
                    writer,
                    sheet_name='daily_quotes',
                    index=True
                )
                
            print(f"Successfully merged daily price data with existing data in 'daily_quotes' sheet")
    
    except ValueError:  # Sheet doesn't exist yet
        # If the sheet doesn't exist, just write the data directly
        with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
            bonds_daily_filtered_df.to_excel(
                writer,
                sheet_name='daily_quotes',
                index=True
            )
        print(f"Created new 'daily_quotes' sheet with daily price data")
        
    # Now handle the monthly_quotes data
    try:
        # Try to read existing data from the monthly_quotes sheet
        existing_monthly_prices = pd.read_excel(output_file, sheet_name='monthly_quotes', index_col=0)
        
        # Ensure bonds_monthly_prices has a datetime index for merging
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
            
        if not isinstance(bonds_monthly_filtered_df.index, pd.DatetimeIndex):
            bonds_monthly_filtered_df.index = pd.to_datetime(bonds_monthly_filtered_df.index)
            
        # Ensure the existing data index is in datetime format
        if not isinstance(existing_monthly_prices.index, pd.DatetimeIndex):
            existing_monthly_prices.index = pd.to_datetime(existing_monthly_prices.index)
        
        # Make sure best_bond_ticker is a valid column in bonds_monthly_filtered_df
        if best_bond_ticker not in bonds_monthly_filtered_df.columns:
            print(f"Warning: {best_bond_ticker} not found in columns. Available columns: {bonds_monthly_filtered_df.columns.tolist()}")
        else:
            # Merge the DataFrames based on the Date index
            merged_monthly_prices = pd.concat([existing_monthly_prices, bonds_monthly_filtered_df[best_bond_ticker]], axis=1)
            # Remove duplicate columns if any
            merged_monthly_prices = merged_monthly_prices.loc[:,~merged_monthly_prices.columns.duplicated()]
            
            # Write the merged data back to Excel
            with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
                merged_monthly_prices.to_excel(
                    writer,
                    sheet_name='monthly_quotes',
                    index=True
                )
                
            print(f"Successfully merged monthly price data with existing data in 'monthly_quotes' sheet")
    
    except ValueError:  # Sheet doesn't exist yet
        # If the sheet doesn't exist, just write the data directly
        # Ensure bonds_monthly_prices has a proper index for Excel export
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
            
        with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
            bonds_monthly_filtered_df.to_excel(
                writer,
                sheet_name='monthly_quotes',
                index=True
            )
        print(f"Created new 'monthly_quotes' sheet with monthly price data")
else:
    # If the file doesn't exist yet, just write both daily and monthly data directly
    with pd.ExcelWriter(output_file, mode='w', engine='openpyxl') as writer:
        bonds_daily_filtered_df.to_excel(
            writer,
            sheet_name='daily_quotes',
            index=True
        )
        
        # Prepare monthly data for export
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
        
        bonds_monthly_filtered_df.to_excel(
            writer,
            sheet_name='monthly_quotes',
            index=True
        )
    print(f"Created new portfolio.xlsx file with 'daily_quotes' and 'monthly_quotes' sheets")

display(bond_funds_sensitivity_df)

Converting best bond index 0 to ticker name TLT
Successfully merged daily price data with existing data in 'daily_quotes' sheet
Successfully merged monthly price data with existing data in 'monthly_quotes' sheet

,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,...,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon,Duration (D*),Price Change Sensitivity,Expected_Return,Standard_Deviation,Sharpe_Ratio
Ticker,,,,,,,,,,,,,,,,,,,,,
TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",46739132001,...,https://www.blackrock.com/us/individual/produc...,0.050,25.72,3.39,0.029,18.109,0.1811,-0.112092,0.162590,-0.952655
ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",597023945,...,https://www.blackrock.com/us/individual/produc...,0.057,21.92,2.35,0.040,14.871,0.1487,-0.050739,0.128063,-0.730417
IGLB,iShares 10+ Year Investment Grade Corporate Bo...,1.10%,6.19%,0.87%,-1.95%,2.09%,4.27%,"Apr 30, 2025","Dec 08, 2009",2507563271,...,https://www.blackrock.com/us/individual/produc...,0.060,22.17,2.17,0.046,14.570,0.1457,-0.027785,0.126813,-0.556608
TLH,iShares 10-20 Year Treasury Bond ETF,4.02%,7.73%,-2.63%,-6.71%,-0.35%,2.95%,"Apr 30, 2025","Jan 05, 2007",9870507317,...,https://www.blackrock.com/us/individual/produc...,0.049,17.11,1.88,0.032,13.173,0.1317,-0.081352,0.128706,-0.964615
ICVT,iShares Convertible Bond ETF,0.45%,13.09%,5.30%,10.75%,0,9.08%,"Apr 30, 2025","Jun 02, 2015",2450374740,...,https://www.blackrock.com/us/individual/produc...,0.030,2.92,1.21,0.021,2.412,0.0241,0.095590,0.150636,0.350449
LQD,iShares iBoxx $ Investment Grade Corporate Bon...,2.22%,7.50%,2.61%,-0.17%,2.37%,4.41%,"Apr 30, 2025","Jul 22, 2002",28839216688,...,https://www.blackrock.com/us/individual/produc...,0.055,12.90,1.11,0.044,9.736,0.0974,-0.007024,0.087784,-0.567574
IGOV,iShares International Treasury Bond ETF,8.65%,9.56%,-0.71%,-3.32%,-0.86%,0.21%,"Apr 30, 2025","Jan 21, 2009",975571043,...,https://www.blackrock.com/us/individual/produc...,0.029,9.58,1.11,0.022,8.529,0.0853,-0.041516,0.096206,-0.876414
LQDI,iShares Inflation Hedged Corporate Bond ETF,2.32%,6.38%,2.12%,4.01%,0,3.95%,"Apr 30, 2025","May 08, 2018",89706518,...,https://www.blackrock.com/us/individual/produc...,0.053,12.45,1.06,0.000,11.690,0.1169,0.036246,0.088271,-0.074248