<a href="https://colab.research.google.com/github/renan-peres/mfin-portfolio-management/blob/main/02_bond_portfolio_contruction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bond Portfolio Selection
Bond selection with convexity > 1 and higher price sensitivity to changes in interest rates.

### Step 1: Import Libraries

In [1]:
# UDFs
from py.utils import load_and_filter_data, export_to_excel
from py.bond_selection import calculate_bond_price, add_bond_prices_to_df, calculate_duration_for_bonds, calculate_modified_duration, calculate_price_change_sensitivity

# Data manipulation libraries
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
from pandas.tseries.offsets import BDay

# Excel libraries
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font
import os

### Step 2: Define Parameters

#### Dates

In [2]:
# Define the date range
end_date = (datetime.today() - BDay(1)).to_pydatetime()  # Subtract 1 business day
# end_date = pd.to_datetime('2025-04-26')                # Report date
start_date = end_date - timedelta(days=5*365)

# Convert datetime objects to Unix timestamps (seconds since Jan 1, 1970)
start_timestamp = int(start_date.timestamp())
end_timestamp = int(end_date.timestamp())

# Print the date range
days_difference = (end_date - start_date).days
print(f"Date Range: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")
print(f"Time span: {days_difference} days ({days_difference/365:.2f} years)")

Date Range: 2020-07-19 to 2025-07-18
Time span: 1825 days (5.00 years)

#### Risk-free rate (T-bill, %)

In [3]:
# Load and process data
daily_risk_free_df = load_and_filter_data('data/datasets/daily_treasury_rates.csv', ['^IRX'], start_date, end_date)
# risk_free_rate = .0433 
risk_free_rate = daily_risk_free_df.iloc[-1, 0] / 100

# Display result
print("Risk-Free Rate:", risk_free_rate, "-- 13 WEEK TREASURY BILL (^IRX)")
daily_risk_free_df.head()

Found 1 of 1 tickers in data/datasets/daily_treasury_rates.csv
Missing tickers: []
Risk-Free Rate: 0.042249999999999996 -- 13 WEEK TREASURY BILL (^IRX)

             ^IRX
Date
2020-07-20  0.105
2020-07-21  0.110
2020-07-22  0.100
2020-07-23  0.103
2020-07-24  0.098

#### Report File

In [4]:
output_file = f'reports/portfolio-{datetime.date(end_date)}.xlsx'

### Step 3: Import Bond Data

In [5]:
blackrock_etf_df = pd.read_csv('data/datasets/fundamentals_blackrock_bonds.csv')
blackrock_etf_df.head()

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,AGG,iShares Core U.S. Aggregate Bond ETF,4.00,6.09,2.55,-0.73,1.72,3.12,"Jun 30, 2025","Sep 22, 2003",127704565505,239458,https://www.blackrock.com/us/individual/produc...,0.0471,8.10,0.49,0.0358
1,AGIH,iShares Inflation Hedged U.S. Aggregate Bond ETF,4.35,5.79,3.01,-,-,2.87,"Jun 30, 2025","Jun 22, 2022",2481623,328179,https://www.blackrock.com/us/individual/produc...,0.0463,7.76,0.48,NaN
2,AGRH,iShares Interest Rate Hedged U.S. Aggregate Bo...,2.20,5.24,5.42,-,-,5.39,"Jun 30, 2025","Jun 22, 2022",7763087,328180,https://www.blackrock.com/us/individual/produc...,0.0528,8.10,-0.21,NaN
3,AGZ,iShares Agency Bond ETF,3.41,5.76,3.12,0.51,1.84,2.35,"Jun 30, 2025","Nov 05, 2008",609788582,239457,https://www.blackrock.com/us/individual/produc...,0.0423,4.10,0.23,0.0359
4,BAIPX,iShares Short-Term TIPS Bond Index Fund,3.92,6.21,3.63,3.41,-,2.80,"Jun 30, 2025","Feb 16, 2016",6159529,282302,https://www.blackrock.com/us/individual/produc...,NaN,NaN,NaN,NaN

### Step 4: Filter for Convexity > 1

In [6]:
bond_funds_filtered_df = blackrock_etf_df[blackrock_etf_df['Convexity'] >= 1].sort_values(by='Convexity', ascending=False).reset_index(drop=True)

# Define all possible percentage columns
all_percentage_cols = ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)', 'Since Inception (%)']

# Filter to only include columns that actually exist in the DataFrame
percentage_cols = [col for col in all_percentage_cols if col in bond_funds_filtered_df.columns]

print(f"Processing the following percentage columns: {percentage_cols}")

# First, ensure all percentage columns are converted to numeric values
for col in percentage_cols:
    # Convert to numeric first, handling errors by setting them to NaN
    bond_funds_filtered_df[col] = pd.to_numeric(bond_funds_filtered_df[col], errors='coerce')

# Now perform the division safely
for col in percentage_cols:
    bond_funds_filtered_df[col] = bond_funds_filtered_df[col] / 100

# Format as percentage strings
for col in percentage_cols + ['Yield_To_Maturity', 'Weighted_Avg_Coupon']:
    # Check if column exists and only process if it does
    if col in bond_funds_filtered_df.columns:
        # Only format cells that aren't NaN
        bond_funds_filtered_df[col] = bond_funds_filtered_df[col].apply(
            lambda x: '{:.2%}'.format(x) if pd.notna(x) else x
        )

bond_tickers = bond_funds_filtered_df['Ticker'].tolist()

# Display Outputs
print(f"Number of iShares bond/fixed income funds with Convexity >= 1: {len(bond_tickers)}")
print(bond_tickers)
display(bond_funds_filtered_df.head())

Processing the following percentage columns: ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)']
Number of iShares bond/fixed income funds with Convexity >= 1: 12
['GOVZ', 'IBGL', 'TLT', 'ILTB', 'IBGB', 'IGLB', 'IBGA', 'TLH', 'LQD', 'IGOV', 'ELQD', 'LQDI']

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,-1.17%,-6.92%,-11.60%,NaN,NaN,-15.61%,"Jun 30, 2025","Sep 22, 2020",266559787,315911,https://www.blackrock.com/us/individual/produc...,5.12%,27.37,7.27,0.00%
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Jun 30, 2025","Mar 25, 2025",3556782,342146,https://www.blackrock.com/us/individual/produc...,5.01%,29.68,3.38,4.67%
2,TLT,iShares 20+ Year Treasury Bond ETF,2.67%,0.17%,-5.04%,-9.18%,-0.32%,3.73%,"Jun 30, 2025","Jul 22, 2002",47121656136,239454,https://www.blackrock.com/us/individual/produc...,5.07%,25.84,3.34,2.93%
3,ILTB,iShares Core 10+ Year USD Bond ETF,3.51%,4.15%,0.69%,-4.17%,2.14%,3.91%,"Jun 30, 2025","Dec 08, 2009",579940188,239424,https://www.blackrock.com/us/individual/produc...,5.65%,21.74,2.31,3.95%
4,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Jun 30, 2025","Mar 25, 2025",3599273,342124,https://www.blackrock.com/us/individual/produc...,5.05%,19.84,2.25,3.48%

In [7]:
# Ensure relevant columns are numeric
bond_funds_filtered_df['Yield_To_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Yield_To_Maturity'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Coupon'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Coupon'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Maturity'], errors='coerce'
)

# Fill missing values with 0
bond_funds_filtered_df = bond_funds_filtered_df.fillna(0)

# Divide the columns by 100 and reassign
bond_funds_filtered_df['Yield_To_Maturity'] = bond_funds_filtered_df['Yield_To_Maturity'] / 100
bond_funds_filtered_df['Weighted_Avg_Coupon'] = bond_funds_filtered_df['Weighted_Avg_Coupon'] / 100

# Display the DataFrame with the updated columns
display(bond_funds_filtered_df.head())

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,-1.17%,-6.92%,-11.60%,0,0,-15.61%,"Jun 30, 2025","Sep 22, 2020",266559787,315911,https://www.blackrock.com/us/individual/produc...,0.0512,27.37,7.27,0.0000
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,0,0,0,0,0,0,"Jun 30, 2025","Mar 25, 2025",3556782,342146,https://www.blackrock.com/us/individual/produc...,0.0501,29.68,3.38,0.0467
2,TLT,iShares 20+ Year Treasury Bond ETF,2.67%,0.17%,-5.04%,-9.18%,-0.32%,3.73%,"Jun 30, 2025","Jul 22, 2002",47121656136,239454,https://www.blackrock.com/us/individual/produc...,0.0507,25.84,3.34,0.0293
3,ILTB,iShares Core 10+ Year USD Bond ETF,3.51%,4.15%,0.69%,-4.17%,2.14%,3.91%,"Jun 30, 2025","Dec 08, 2009",579940188,239424,https://www.blackrock.com/us/individual/produc...,0.0565,21.74,2.31,0.0395
4,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,0,0,0,0,0,0,"Jun 30, 2025","Mar 25, 2025",3599273,342124,https://www.blackrock.com/us/individual/produc...,0.0505,19.84,2.25,0.0348

### Step 5: Import Quotes

In [8]:
bond_tickers = bond_funds_filtered_df['Ticker'].tolist()
print(bond_tickers)

['GOVZ', 'IBGL', 'TLT', 'ILTB', 'IBGB', 'IGLB', 'IBGA', 'TLH', 'LQD', 'IGOV', 'ELQD', 'LQDI']

In [9]:
# Load and process data
bonds_daily_df = load_and_filter_data('data/datasets/daily_bond_quotes.csv', bond_tickers, start_date, end_date)
display(bonds_daily_df.head())

Found 9 of 12 tickers in data/datasets/daily_bond_quotes.csv
Missing tickers: ['IBGL', 'IBGB', 'IBGA']

            ELQD  GOVZ   IGLB   IGOV   ILTB     LQD   LQDI     TLH     TLT
Date
2020-07-20   NaN   NaN  59.66  51.33  64.16  116.97  23.33  146.00  146.29
2020-07-21   NaN   NaN  59.78  51.72  64.21  117.13  23.42  146.22  146.37
2020-07-22   NaN   NaN  60.04  51.90  64.54  117.51  23.58  146.37  146.81
2020-07-23   NaN   NaN  60.32  51.96  64.87  117.59  23.67  147.29  148.53
2020-07-24   NaN   NaN  60.23  52.11  64.81  117.33  23.50  147.27  148.52

### Step 6: Prepare Data (Drop Invalid Tickers)

#### Daily Quotes

In [10]:
# Identify columns with null values in first or last 50 rows
first_50_nulls = bonds_daily_df.head(50).isnull().any()
last_50_nulls = bonds_daily_df.tail(50).isnull().any()

# Columns to drop are those with nulls in first 50 OR last 50 rows
columns_to_drop = first_50_nulls | last_50_nulls
bad_columns = columns_to_drop[columns_to_drop].index.tolist()

print(f"Dropping {len(bad_columns)} columns with missing values in first/last 50 records: {bad_columns}")

# Drop those columns
bonds_daily_filtered_df = bonds_daily_df.loc[:, ~columns_to_drop]

# Display the cleaned dataframe
display(bonds_daily_filtered_df.head())

Dropping 2 columns with missing values in first/last 50 records: ['ELQD', 'GOVZ']

             IGLB   IGOV   ILTB     LQD   LQDI     TLH     TLT
Date
2020-07-20  59.66  51.33  64.16  116.97  23.33  146.00  146.29
2020-07-21  59.78  51.72  64.21  117.13  23.42  146.22  146.37
2020-07-22  60.04  51.90  64.54  117.51  23.58  146.37  146.81
2020-07-23  60.32  51.96  64.87  117.59  23.67  147.29  148.53
2020-07-24  60.23  52.11  64.81  117.33  23.50  147.27  148.52

#### Monthly Quotes

In [11]:
bonds_monthly_filtered_df = (bonds_daily_filtered_df.set_index(pd.to_datetime(bonds_daily_filtered_df.pop('Date')))
      if 'Date' in bonds_daily_filtered_df.columns else bonds_daily_filtered_df.copy())
bonds_monthly_filtered_df.index = pd.to_datetime(bonds_monthly_filtered_df.index)              
bonds_monthly_filtered_df = (bonds_monthly_filtered_df.resample('MS').last()
   .reset_index()
   .rename(columns={'index': 'Date'}))

bonds_monthly_filtered_df.set_index('Date', inplace=True)
display(bonds_monthly_filtered_df.head())

             IGLB   IGOV   ILTB     LQD   LQDI     TLH     TLT
Date
2020-07-01  60.35  52.75  65.17  117.53  23.49  148.27  149.62
2020-08-01  58.16  52.80  62.75  115.44  23.77  142.85  142.07
2020-09-01  58.00  52.31  62.61  114.93  23.62  143.94  143.17
2020-10-01  57.35  52.41  61.50  114.34  23.75  139.90  138.32
2020-11-01  60.79  53.70  64.19  118.65  24.56  141.38  140.62

### Step 7: Calculate Returns (Lognormal)

In [12]:
log_returns_df = np.log(bonds_daily_filtered_df / bonds_daily_filtered_df.shift(1))
log_returns_df = log_returns_df.dropna().sort_index(axis=0, ascending=True).sort_index(axis=1, ascending=True)
log_returns_df.head()

,IGLB,IGOV,ILTB,LQD,LQDI,TLH,TLT
Date,,,,,,,
2020-07-21,0.002009,0.007569,0.000779,0.001367,0.003850,0.001506,0.000547
2020-07-22,0.004340,0.003474,0.005126,0.003239,0.006809,0.001025,0.003002
2020-07-23,0.004653,0.001155,0.005100,0.000681,0.003810,0.006266,0.011648
2020-07-24,-0.001493,0.002883,-0.000925,-0.002214,-0.007208,-0.000136,-0.000067
2020-07-27,-0.004493,0.009169,-0.003865,-0.003073,-0.001277,-0.003605,-0.003710

### Step 8: Calculate Bond Metrics

#### Bond Price (PV)

In [13]:
# Apply the function to your DataFrame
bond_funds_price_df = add_bond_prices_to_df(bond_funds_filtered_df)

# Display the updated DataFrame with bond prices
bond_funds_price_df[['Ticker', 'Weighted_Avg_Maturity', 'Weighted_Avg_Coupon', 
                      'Yield_To_Maturity', 'Bond_Price']]

,Ticker,Weighted_Avg_Maturity,Weighted_Avg_Coupon,Yield_To_Maturity,Bond_Price
0,GOVZ,27.37,0.000,0.051,25.065
1,IBGL,29.68,0.047,0.050,94.776
2,TLT,25.84,0.029,0.051,69.366
3,ILTB,21.74,0.040,0.056,78.872
4,IBGB,19.84,0.035,0.050,80.469
5,IGLB,22.01,0.046,0.059,83.985
6,IBGA,18.93,0.040,0.050,87.630
7,TLH,17.05,0.032,0.050,79.906
8,LQD,12.80,0.044,0.053,91.988
9,IGOV,9.52,0.022,0.029,94.466
10,ELQD,12.32,0.041,0.053,89.489
11,LQDI,12.37,0.000,0.051,53.571

#### Modified Duration (D*)

In [14]:
bond_tickers = bonds_daily_filtered_df.columns.tolist()
bond_funds_filtered_df = bond_funds_filtered_df[bond_funds_filtered_df['Ticker'].isin(bond_tickers)].reset_index(drop=True)

# Apply the function to your DataFrame
bond_funds_duration_df = calculate_duration_for_bonds(bond_funds_filtered_df, end_date)

# Display the updated DataFrame
print(bond_tickers)
bond_funds_duration_df[['Ticker', 'Weighted_Avg_Maturity', 'Weighted_Avg_Coupon', 'Yield_To_Maturity', 'Bond_Price', 'Duration (D*)', 'Convexity']]

['IGLB', 'IGOV', 'ILTB', 'LQD', 'LQDI', 'TLH', 'TLT']

,Ticker,Weighted_Avg_Maturity,Weighted_Avg_Coupon,Yield_To_Maturity,Bond_Price,Duration (D*),Convexity
0,TLT,25.84,0.029,0.051,69.366,17.988,3.34
1,ILTB,21.74,0.040,0.056,78.872,14.881,2.31
2,IGLB,22.01,0.046,0.059,83.985,14.601,2.15
3,TLH,17.05,0.032,0.050,79.906,13.127,1.85
4,LQD,12.80,0.044,0.053,91.988,9.743,1.10
5,IGOV,9.52,0.022,0.029,94.466,8.519,1.08
6,LQDI,12.37,0.000,0.051,53.571,11.701,1.05

#### Price Sensitivity to Changes in YTM (-1%)

In [15]:
# Apply the function to your DataFrame
bond_funds_sensitivity_df = calculate_price_change_sensitivity(bond_funds_duration_df)
bond_funds_sensitivity_df[['Ticker', 'Bond_Price', 'Duration (D*)', 'Convexity', 'Price Sensitivity to YTM (-1%)']]

  Ticker  Bond_Price  Duration (D*)  Convexity  Price Sensitivity to YTM (-1%)
0    TLT      69.366         17.988       3.34                          0.1799
1   ILTB      78.872         14.881       2.31                          0.1488
2   IGLB      83.985         14.601       2.15                          0.1460
3    TLH      79.906         13.127       1.85                          0.1313
4    LQD      91.988          9.743       1.10                          0.0974
5   IGOV      94.466          8.519       1.08                          0.0852
6   LQDI      53.571         11.701       1.05                          0.1170

### Step 9: Select the Best Bond (Highest Price Sentivity to Changes in YTM)

In [16]:
# Find the row index where Price Sensitivity to YTM (-1%) is at its maximum
best_bond_ticker = bond_funds_sensitivity_df["Price Sensitivity to YTM (-1%)"].idxmax()

# Get the maximum value for display
max_sensitivity = bond_funds_sensitivity_df["Price Sensitivity to YTM (-1%)"].max()

print(f"Best Bond Ticker: {best_bond_ticker}")
print(f"Maximum Price Sensitivity to YTM (-1%): {max_sensitivity:.6f}")
bond_funds_sensitivity_df.loc[best_bond_ticker]

Best Bond Ticker: 0
Maximum Price Sensitivity to YTM (-1%): 0.179900

Ticker                                                                          TLT
Name                                             iShares 20+ Year Treasury Bond ETF
YTD (%)                                                                       2.67%
1Y (%)                                                                        0.17%
3Y (%)                                                                       -5.04%
5Y (%)                                                                       -9.18%
10Y (%)                                                                      -0.32%
Incept (%)                                                                    3.73%
Perf. as of                                                            Jun 30, 2025
Inception Date                                                         Jul 22, 2002
Net Assets                                                              47121656136
Product_ID                                                                   239454
URL                               https://www.blackrock.com/us/individual/produc...
Yield_To_Maturity                                                             0.051
Weighted_Avg_Maturity                                                         25.84
Convexity                                                                      3.34
Weighted_Avg_Coupon                                                           0.029
Bond_Price                                                                   69.366
Duration (D*)                                                                17.988
Price Sensitivity to YTM (-1%)                                               0.1799
Name: 0, dtype: object

### Step 10: Add Returns and Standard Deviation to DataFrame

In [17]:
# Step 1: Unpivot (melt) the log_returns_df
log_returns_long = log_returns_df.reset_index().melt(id_vars='Date', var_name='Ticker', value_name='Log Return')

# Step 2: Ensure 'Log Return' column is numeric
log_returns_long['Log Return'] = pd.to_numeric(log_returns_long['Log Return'], errors='coerce')

# Step 3: Drop rows with NaN values in 'Log Return'
log_returns_long = log_returns_long.dropna(subset=['Log Return'])

# Step 4: Calculate statistics for each ticker
log_returns_stats = log_returns_long.groupby('Ticker').agg(
    Expected_Return=('Log Return', lambda x: ((1 + x).prod() ** (252 / len(x))) - 1),  # Geometric mean (annualized return)
    Standard_Deviation=('Log Return', lambda x: x.std() * np.sqrt(252))  # Annualized standard deviation
).reset_index()

# Step 6: Set Index
log_returns_stats.set_index('Ticker', inplace=True)

# Step 7: Merge with bond_funds_sensitivity_df
bond_funds_sensitivity_df = bond_funds_sensitivity_df.merge(
    log_returns_stats,
    on='Ticker',
    how='left'
)

# Step 7: Set Index
bond_funds_sensitivity_df.set_index('Ticker', inplace=True)

# Display the updated DataFrame
display(bond_funds_sensitivity_df)

,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,...,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon,Bond_Price,Duration (D*),Price Sensitivity to YTM (-1%),Expected_Return,Standard_Deviation
Ticker,,,,,,,,,,,,,,,,,,,,,
TLT,iShares 20+ Year Treasury Bond ETF,2.67%,0.17%,-5.04%,-9.18%,-0.32%,3.73%,"Jun 30, 2025","Jul 22, 2002",47121656136,...,https://www.blackrock.com/us/individual/produc...,0.051,25.84,3.34,0.029,69.366,17.988,0.1799,-0.114910,0.162201
ILTB,iShares Core 10+ Year USD Bond ETF,3.51%,4.15%,0.69%,-4.17%,2.14%,3.91%,"Jun 30, 2025","Dec 08, 2009",579940188,...,https://www.blackrock.com/us/individual/produc...,0.056,21.74,2.31,0.040,78.872,14.881,0.1488,-0.064081,0.128672
IGLB,iShares 10+ Year Investment Grade Corporate Bo...,3.66%,5.36%,2.95%,-2.25%,2.91%,4.39%,"Jun 30, 2025","Dec 08, 2009",2327671177,...,https://www.blackrock.com/us/individual/produc...,0.059,22.01,2.15,0.046,83.985,14.601,0.1460,-0.046423,0.126698
TLH,iShares 10-20 Year Treasury Bond ETF,3.72%,3.06%,-1.76%,-6.64%,-0.15%,2.91%,"Jun 30, 2025","Jan 05, 2007",11192760856,...,https://www.blackrock.com/us/individual/produc...,0.050,17.05,1.85,0.032,79.906,13.127,0.1313,-0.083384,0.128966
LQD,iShares iBoxx $ Investment Grade Corporate Bon...,4.50%,6.92%,4.13%,-0.50%,2.88%,4.48%,"Jun 30, 2025","Jul 22, 2002",27466586618,...,https://www.blackrock.com/us/individual/produc...,0.053,12.80,1.10,0.044,91.988,9.743,0.0974,-0.020002,0.087681
IGOV,iShares International Treasury Bond ETF,11.93%,11.97%,2.02%,-3.10%,-0.20%,0.39%,"Jun 30, 2025","Jan 21, 2009",1274829562,...,https://www.blackrock.com/us/individual/produc...,0.029,9.52,1.08,0.022,94.466,8.519,0.0852,-0.043215,0.096890
LQDI,iShares Inflation Hedged Corporate Bond ETF,4.97%,6.58%,4.76%,3.33%,0,4.22%,"Jun 30, 2025","May 08, 2018",91883106,...,https://www.blackrock.com/us/individual/produc...,0.051,12.37,1.05,0.000,53.571,11.701,0.1170,0.019494,0.086270

### Step 11: Export Data to Excel

In [18]:
# Check if best_bond_ticker is a numeric index instead of ticker name
if isinstance(best_bond_ticker, (int, np.integer)):
    # Get the actual ticker name from the dataframe
    if 'Ticker' in bond_funds_sensitivity_df.columns:
        best_bond_ticker = bond_funds_sensitivity_df.iloc[best_bond_ticker]['Ticker']
        print(f"Using ticker name: {best_bond_ticker}")
    else:
        # If Ticker is the index name
        best_bond_ticker = bond_funds_sensitivity_df.index[best_bond_ticker]
        print(f"Using ticker name from index: {best_bond_ticker}")

export_to_excel(output_file, {
    'bond': bond_funds_sensitivity_df,
    'daily_quotes': bonds_daily_filtered_df[[best_bond_ticker]],  
    'monthly_quotes': bonds_monthly_filtered_df[[best_bond_ticker]]   
})

Using ticker name from index: TLT
Updated sheet 'bond'
Successfully merged data into 'daily_quotes' sheet
Successfully merged data into 'monthly_quotes' sheet
Successfully exported all data to reports/portfolio-2025-07-18.xlsx