## Import Libraries

In [1]:
# %pip install -r requirements.txt
import numpy as np
import pandas as pd

### Step 1: Define Parameters

#### Dates

In [2]:
from datetime import datetime, timedelta
from pandas.tseries.offsets import BDay

# Time Range
# Adjust end_date to the last business day
end_date = (datetime.today() - BDay(1)).to_pydatetime()  # Subtract 1 business day
start_date = end_date - timedelta(days=5*365)

#### Risk-free rate (T-bill, %)

In [3]:
def load_and_filter_data(file_path, tickers, start_date, end_date):
    df = pd.read_csv(file_path)

    # Filter columns to available tickers
    available_tickers = [ticker for ticker in tickers if ticker in df.columns]
    print(f"Found {len(available_tickers)} of {len(tickers)} tickers in {file_path}")
    print(f"Missing tickers: {[ticker for ticker in tickers if ticker not in df.columns]}")

    columns_to_keep = ['Date'] + available_tickers if 'Date' in df.columns else available_tickers
    df = df[columns_to_keep] if all(col in df.columns for col in columns_to_keep) else df

    # Handle Date column or index
    if 'Date' in df.columns:
        df['Date'] = pd.to_datetime(df['Date'])
        df = df[(df['Date'] >= start_date) & (df['Date'] <= end_date)]
        df = df.set_index('Date')
    else:
        df.index = pd.to_datetime(df.index)
        df = df.loc[start_date:end_date]

    return df.sort_index(axis=0).sort_index(axis=1)

# Load and process data
daily_risk_free_df = load_and_filter_data('data/datasets/daily_treasury_rates.csv', ['^IRX'], start_date, end_date)
# risk_free_rate = .0433 
risk_free_rate = daily_risk_free_df.iloc[-1, 0] / 100

# Display result
print("Risk-Free Rate:", risk_free_rate, "-- 13 WEEK TREASURY BILL (^IRX)")
daily_risk_free_df.head()

Found 1 of 1 tickers in data/datasets/daily_treasury_rates.csv
Missing tickers: []
Risk-Free Rate: 0.042199999999999994 -- 13 WEEK TREASURY BILL (^IRX)

             ^IRX
Date
2020-05-11  0.105
2020-05-12  0.123
2020-05-13  0.115
2020-05-14  0.105
2020-05-15  0.103

### Step 2: Import Bond Data

In [4]:
blackrock_etf_df = pd.read_csv('data/datasets/fundamentals_blackrock_bonds.csv')
blackrock_etf_df.head()

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,AGG,iShares Core U.S. Aggregate Bond ETF,3.16,8.00,1.96,-0.68,1.50,3.10,"Apr 30, 2025","Sep 22, 2003",123015824067,239458,https://www.blackrock.com/us/individual/produc...,0.0474,8.16,0.53,0.0354
1,AGIH,iShares Inflation Hedged U.S. Aggregate Bond ETF,3.42,7.17,-,-,-,2.72,"Apr 30, 2025","Jun 22, 2022",2461195,328179,https://www.blackrock.com/us/individual/produc...,0.0468,7.77,0.49,NaN
2,AGRH,iShares Interest Rate Hedged U.S. Aggregate Bo...,0.77,4.50,-,-,-,5.19,"Apr 30, 2025","Jun 22, 2022",7727535,328180,https://www.blackrock.com/us/individual/produc...,0.0533,8.14,-0.16,NaN
3,AGZ,iShares Agency Bond ETF,2.85,6.98,2.84,0.48,1.74,2.34,"Apr 30, 2025","Nov 05, 2008",609341356,239457,https://www.blackrock.com/us/individual/produc...,0.0423,4.15,0.24,0.0346
4,BAIPX,iShares Short-Term TIPS Bond Index Fund,3.76,7.54,3.19,3.67,-,2.83,"Apr 30, 2025","Feb 16, 2016",5288869,282302,https://www.blackrock.com/us/individual/produc...,NaN,NaN,NaN,NaN

### Step 3: Filter for Convexity > 1

In [5]:
bond_funds_filtered_df = blackrock_etf_df[blackrock_etf_df['Convexity'] >= 1].sort_values(by='Convexity', ascending=False).reset_index(drop=True)

# Define all possible percentage columns
all_percentage_cols = ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)', 'Since Inception (%)']

# Filter to only include columns that actually exist in the DataFrame
percentage_cols = [col for col in all_percentage_cols if col in bond_funds_filtered_df.columns]

print(f"Processing the following percentage columns: {percentage_cols}")

# First, ensure all percentage columns are converted to numeric values
for col in percentage_cols:
    # Convert to numeric first, handling errors by setting them to NaN
    bond_funds_filtered_df[col] = pd.to_numeric(bond_funds_filtered_df[col], errors='coerce')

# Now perform the division safely
for col in percentage_cols:
    bond_funds_filtered_df[col] = bond_funds_filtered_df[col] / 100

# Format as percentage strings
for col in percentage_cols + ['Yield_To_Maturity', 'Weighted_Avg_Coupon']:
    # Check if column exists and only process if it does
    if col in bond_funds_filtered_df.columns:
        # Only format cells that aren't NaN
        bond_funds_filtered_df[col] = bond_funds_filtered_df[col].apply(
            lambda x: '{:.2%}'.format(x) if pd.notna(x) else x
        )

bond_tickers = bond_funds_filtered_df['Ticker'].tolist()

# Display Outputs
print(f"Number of iShares bond/fixed income funds with Convexity >= 1: {len(bond_tickers)}")
print(bond_tickers)
display(bond_funds_filtered_df.head())

Processing the following percentage columns: ['YTD (%)', '1Y (%)', '3Y (%)', '5Y (%)', '10Y (%)', 'Incept (%)']
Number of iShares bond/fixed income funds with Convexity >= 1: 13
['GOVZ', 'IBGL', 'TLT', 'IBGB', 'ILTB', 'IGLB', 'IBGA', 'TLH', 'ICVT', 'IGOV', 'LQD', 'ELQD', 'LQDI']

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,0.65%,1.05%,-12.71%,NaN,NaN,-15.79%,"Apr 30, 2025","Sep 22, 2020",252218794,315911,https://www.blackrock.com/us/individual/produc...,4.96%,27.32,7.26,0.00%
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Apr 30, 2025","Mar 25, 2025",3646157,342146,https://www.blackrock.com/us/individual/produc...,4.85%,29.77,3.51,4.63%
2,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",47129940736,239454,https://www.blackrock.com/us/individual/produc...,4.93%,25.73,3.41,2.86%
3,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,NaN,NaN,NaN,NaN,NaN,NaN,"Apr 30, 2025","Mar 25, 2025",3664035,342124,https://www.blackrock.com/us/individual/produc...,4.92%,19.97,2.36,3.18%
4,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",599704097,239424,https://www.blackrock.com/us/individual/produc...,5.65%,21.92,2.35,3.95%

In [6]:
# Ensure relevant columns are numeric
bond_funds_filtered_df['Yield_To_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Yield_To_Maturity'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Coupon'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Coupon'].str.replace('%', ''), errors='coerce'
)
bond_funds_filtered_df['Weighted_Avg_Maturity'] = pd.to_numeric(
    bond_funds_filtered_df['Weighted_Avg_Maturity'], errors='coerce'
)

# Fill missing values with 0
bond_funds_filtered_df = bond_funds_filtered_df.fillna(0)

# Divide the columns by 100 and reassign
bond_funds_filtered_df['Yield_To_Maturity'] = bond_funds_filtered_df['Yield_To_Maturity'] / 100
bond_funds_filtered_df['Weighted_Avg_Coupon'] = bond_funds_filtered_df['Weighted_Avg_Coupon'] / 100

# Display the DataFrame with the updated columns
display(bond_funds_filtered_df.head())

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,Product_ID,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon
0,GOVZ,iShares 25+ Year Treasury STRIPS Bond ETF,0.65%,1.05%,-12.71%,0,0,-15.79%,"Apr 30, 2025","Sep 22, 2020",252218794,315911,https://www.blackrock.com/us/individual/produc...,0.0496,27.32,7.26,0.0000
1,IBGL,iShares® iBonds® Dec 2055 Term Treasury ETF,0,0,0,0,0,0,"Apr 30, 2025","Mar 25, 2025",3646157,342146,https://www.blackrock.com/us/individual/produc...,0.0485,29.77,3.51,0.0463
2,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",47129940736,239454,https://www.blackrock.com/us/individual/produc...,0.0493,25.73,3.41,0.0286
3,IBGB,iShares® iBonds® Dec 2045 Term Treasury ETF,0,0,0,0,0,0,"Apr 30, 2025","Mar 25, 2025",3664035,342124,https://www.blackrock.com/us/individual/produc...,0.0492,19.97,2.36,0.0318
4,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",599704097,239424,https://www.blackrock.com/us/individual/produc...,0.0565,21.92,2.35,0.0395

### Step 4: Download Adjusted Closing Prices (5Y)

In [7]:
bond_tickers = bond_funds_filtered_df['Ticker'].tolist()

In [8]:
from py.fetch_price_history import fetch_price_history_openbb
from dotenv import load_dotenv
load_dotenv()
import os
from openbb import obb
import polars as pl
obb.user.credentials.fmp_api_key = os.getenv("FMP_API_KEY")

###########################################################
# DAILY DATA
###########################################################

daily_output = 'data/datasets/daily_bond_quotes.csv'

bonds_daily_df, failed_daily = fetch_price_history_openbb(
    bond_tickers, 
    start_date, 
    end_date,
    interval='1d',
    data_file=daily_output,
    provider='fmp'  # yfinance
)

###########################################################
# MONTHLY DATA
###########################################################

monthly_output = 'data/datasets/monthly_bond_quotes.csv'

bonds_monthly_prices = (bonds_daily_df.set_index(pd.to_datetime(bonds_daily_df.pop('Date')))
      if 'Date' in bonds_daily_df.columns else bonds_daily_df.copy())
bonds_monthly_prices.index = pd.to_datetime(bonds_monthly_prices.index)              
bonds_monthly_prices = (bonds_monthly_prices.resample('MS').last()
   .reset_index()
   .rename(columns={'index': 'Date'}))

# Save to CSV
bonds_monthly_prices.to_csv(monthly_output, index=False)

display(bonds_monthly_prices.head())

📂 Reading existing data from: data/datasets/daily_bond_quotes.csv
🗓 Existing data: 2020-05-06 to 2025-05-09
✅ Found 13 tickers, ❌ Missing 0 tickers
✅ Data is already up-to-date and complete

,Date,ELQD,GOVZ,IBGA,IBGB,IBGL,ICVT,IGLB,IGOV,ILTB,LQD,LQDI,TLH,TLT
0,2020-05-01,NaN,NaN,NaN,NaN,NaN,54.97,55.43,49.74,60.61,111.62,21.93,143.98,142.79
1,2020-06-01,NaN,NaN,NaN,NaN,NaN,59.46,57.22,50.36,61.71,113.99,22.55,144.24,143.27
2,2020-07-01,NaN,NaN,NaN,NaN,NaN,63.86,60.35,52.75,65.17,117.53,23.49,148.27,149.62
3,2020-08-01,NaN,NaN,NaN,NaN,NaN,70.40,58.16,52.80,62.75,115.44,23.77,142.85,142.07
4,2020-09-01,NaN,21.44,NaN,NaN,NaN,67.84,58.00,52.31,62.61,114.93,23.62,143.94,143.17

### Step 5: Prepare Data (Drop Invalid Tickers)

In [9]:
# Identify columns with null values in first or last 50 rows
first_50_nulls = bonds_daily_df.head(50).isnull().any()
last_50_nulls = bonds_daily_df.tail(50).isnull().any()

# Columns to drop are those with nulls in first 50 OR last 50 rows
columns_to_drop = first_50_nulls | last_50_nulls
bad_columns = columns_to_drop[columns_to_drop].index.tolist()

print(f"Dropping {len(bad_columns)} columns with missing values in first/last 50 records: {bad_columns}")

# Drop those columns
bonds_daily_filtered_df = bonds_daily_df.loc[:, ~columns_to_drop]

# Display the first few rows of the cleaned dataframe
bonds_daily_filtered_df.head()

Dropping 6 columns with missing values in first/last 50 records: ['ELQD', 'GOVZ', 'IBGA', 'IBGB', 'IBGL', 'ICVT']

             IGLB   IGOV   ILTB     LQD   LQDI     TLH     TLT
Date
2020-05-06  53.13  48.79  58.61  107.31  20.99  143.50  142.63
2020-05-07  53.19  48.89  59.09  107.60  21.04  145.25  145.02
2020-05-08  52.76  48.94  58.63  107.08  20.78  144.06  143.13
2020-05-11  52.16  48.65  58.15  106.15  20.82  143.14  142.01
2020-05-12  52.70  48.86  58.72  107.17  21.02  144.05  143.47

### Step 6: Calculate Returns (Lognormal)

In [10]:
log_returns_df = np.log(bonds_daily_filtered_df / bonds_daily_filtered_df.shift(1))
log_returns_df = log_returns_df.dropna().sort_index(axis=0, ascending=True).sort_index(axis=1, ascending=True)
log_returns_df.head()

,IGLB,IGOV,ILTB,LQD,LQDI,TLH,TLT
Date,,,,,,,
2020-05-07,0.001129,0.002048,0.008156,0.002699,0.002379,0.012121,0.016618
2020-05-08,-0.008117,0.001022,-0.007815,-0.004844,-0.012434,-0.008227,-0.013118
2020-05-11,-0.011437,-0.005943,-0.008221,-0.008723,0.001923,-0.006407,-0.007856
2020-05-12,0.010300,0.004307,0.009755,0.009563,0.009560,0.006337,0.010228
2020-05-13,0.000000,0.001227,0.005435,0.002237,-0.004291,0.004018,0.006946

### Step 7: Calculate Modified Duration (D*)

In [11]:
def calculate_modified_duration(settlement_date, maturity_date, coupon_rate, ytm, frequency):
    total_years = (maturity_date - settlement_date).days / 365
    num_periods = int(total_years * frequency)
    face_value, coupon_payment = 100, coupon_rate * 100 / frequency
    cash_flows = np.full(num_periods, coupon_payment)
    cash_flows[-1] += face_value
    times = np.arange(1, num_periods + 1) / frequency
    discounted_cash_flows = cash_flows / (1 + ytm / frequency) ** times
    macaulay_duration = (times * discounted_cash_flows).sum() / discounted_cash_flows.sum()
    return macaulay_duration / (1 + ytm / frequency)

def calculate_duration_for_bonds(df):
    df['Duration (D*)'] = df.apply(lambda row: calculate_modified_duration(
        end_date,
        end_date + timedelta(days=int(row['Weighted_Avg_Maturity'] * 365)),
        row['Weighted_Avg_Coupon'], row['Yield_To_Maturity'], 2
    ) if pd.notna(row['Yield_To_Maturity']) and pd.notna(row['Weighted_Avg_Coupon']) and pd.notna(row['Weighted_Avg_Maturity']) else np.nan, axis=1)
    return df.round(3)

bond_tickers = bonds_daily_filtered_df.columns.tolist()
bond_funds_filtered_df = bond_funds_filtered_df[bond_funds_filtered_df['Ticker'].isin(bond_tickers)].reset_index(drop=True)

# Apply the function to your DataFrame
bond_funds_duration_df = calculate_duration_for_bonds(bond_funds_filtered_df)

# Display the updated DataFrame
print(bond_tickers)
bond_funds_duration_df[['Ticker', 'Weighted_Avg_Maturity', 'Weighted_Avg_Coupon', 'Yield_To_Maturity', 'Duration (D*)', 'Convexity']]

['IGLB', 'IGOV', 'ILTB', 'LQD', 'LQDI', 'TLH', 'TLT']

,Ticker,Weighted_Avg_Maturity,Weighted_Avg_Coupon,Yield_To_Maturity,Duration (D*),Convexity
0,TLT,25.73,0.029,0.049,18.131,3.41
1,ILTB,21.92,0.040,0.056,14.881,2.35
2,IGLB,22.13,0.046,0.060,14.583,2.17
3,TLH,17.12,0.032,0.048,13.185,1.89
4,IGOV,9.64,0.022,0.028,8.535,1.12
5,LQD,12.87,0.044,0.054,9.740,1.11
6,LQDI,12.41,0.000,0.053,11.691,1.05

### Step 8: Calculate Price Sensitivity with Convexity (Changes in YTM)

In [12]:
def calculate_price_change_sensitivity(df, rate_change=-0.01):
    """
    Calculate price change sensitivity using Duration (D*) and Convexity.
    
    Parameters:
    - df: DataFrame containing 'Duration (D*)' and 'Convexity' columns.
    - rate_change: Change in interest rates (default is -1% or -0.01).
    
    Returns:
    - Updated DataFrame with 'Price Change Sensitivity' column.
    """
    df['Price Change Sensitivity'] = df.apply(
        lambda row: row['Duration (D*)'] + 0.5 * row['Convexity'] * (rate_change ** 2)
        if pd.notna(row['Duration (D*)']) and pd.notna(row['Convexity']) else np.nan,
        axis=1
    ) / 100
    return df.round(4)

# Apply the function to your DataFrame
bond_funds_sensitivity_df = calculate_price_change_sensitivity(bond_funds_duration_df)
bond_funds_sensitivity_df[['Ticker', 'Duration (D*)', 'Convexity', 'Price Change Sensitivity']]

  Ticker  Duration (D*)  Convexity  Price Change Sensitivity
0    TLT         18.131       3.41                    0.1813
1   ILTB         14.881       2.35                    0.1488
2   IGLB         14.583       2.17                    0.1458
3    TLH         13.185       1.89                    0.1319
4   IGOV          8.535       1.12                    0.0854
5    LQD          9.740       1.11                    0.0974
6   LQDI         11.691       1.05                    0.1169

### Step 9: Select the Best Bond (Highest Price Change Sensitivity)

In [13]:
# Find the row index where Price Change Sensitivity is at its maximum
best_bond_ticker = bond_funds_sensitivity_df["Price Change Sensitivity"].idxmax()

# Get the maximum value for display
max_sensitivity = bond_funds_sensitivity_df["Price Change Sensitivity"].max()

print(f"Best Bond Ticker: {best_bond_ticker}")
print(f"Maximum Price Change Sensitivity: {max_sensitivity:.6f}")
bond_funds_sensitivity_df.loc[best_bond_ticker]

Best Bond Ticker: 0
Maximum Price Change Sensitivity: 0.181300

Ticker                                                                    TLT
Name                                       iShares 20+ Year Treasury Bond ETF
YTD (%)                                                                 3.23%
1Y (%)                                                                  5.46%
3Y (%)                                                                 -6.03%
5Y (%)                                                                 -9.43%
10Y (%)                                                                -0.87%
Incept (%)                                                              3.79%
Perf. as of                                                      Apr 30, 2025
Inception Date                                                   Jul 22, 2002
Net Assets                                                        47129940736
Product_ID                                                             239454
URL                         https://www.blackrock.com/us/individual/produc...
Yield_To_Maturity                                                       0.049
Weighted_Avg_Maturity                                                   25.73
Convexity                                                                3.41
Weighted_Avg_Coupon                                                     0.029
Duration (D*)                                                          18.131
Price Change Sensitivity                                               0.1813
Name: 0, dtype: object

### Step 10: Add Returns and Standard Deviation to DataFrame

In [14]:
# Step 1: Unpivot (melt) the log_returns_df
log_returns_long = log_returns_df.reset_index().melt(id_vars='Date', var_name='Ticker', value_name='Log Return')

# Step 2: Ensure 'Log Return' column is numeric
log_returns_long['Log Return'] = pd.to_numeric(log_returns_long['Log Return'], errors='coerce')

# Step 3: Drop rows with NaN values in 'Log Return'
log_returns_long = log_returns_long.dropna(subset=['Log Return'])

# Step 4: Calculate statistics for each ticker
log_returns_stats = log_returns_long.groupby('Ticker').agg(
    Expected_Return=('Log Return', lambda x: ((1 + x).prod() ** (252 / len(x))) - 1),  # Geometric mean (annualized return)
    Standard_Deviation=('Log Return', lambda x: x.std() * np.sqrt(252))  # Annualized standard deviation
).reset_index()

# Step 5: Calculate Sharpe Ratio
log_returns_stats['Sharpe_Ratio'] = (log_returns_stats['Expected_Return'] - risk_free_rate) / log_returns_stats['Standard_Deviation']

# Step 6: Set Index
log_returns_stats.set_index('Ticker', inplace=True)

# Step 7: Merge with bond_funds_sensitivity_df
bond_funds_sensitivity_df = bond_funds_sensitivity_df.merge(
    log_returns_stats,
    on='Ticker',
    how='left'
)

# Display the updated DataFrame
display(bond_funds_sensitivity_df)

,Ticker,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,...,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon,Duration (D*),Price Change Sensitivity,Expected_Return,Standard_Deviation,Sharpe_Ratio
0,TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",...,https://www.blackrock.com/us/individual/produc...,0.049,25.73,3.41,0.029,18.131,0.1813,-0.106034,0.162693,-0.911122
1,ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",...,https://www.blackrock.com/us/individual/produc...,0.056,21.92,2.35,0.040,14.881,0.1488,-0.046370,0.128154,-0.691117
2,IGLB,iShares 10+ Year Investment Grade Corporate Bo...,1.10%,6.19%,0.87%,-1.95%,2.09%,4.27%,"Apr 30, 2025","Dec 08, 2009",...,https://www.blackrock.com/us/individual/produc...,0.060,22.13,2.17,0.046,14.583,0.1458,-0.026215,0.127023,-0.538599
3,TLH,iShares 10-20 Year Treasury Bond ETF,4.02%,7.73%,-2.63%,-6.71%,-0.35%,2.95%,"Apr 30, 2025","Jan 05, 2007",...,https://www.blackrock.com/us/individual/produc...,0.048,17.12,1.89,0.032,13.185,0.1319,-0.077101,0.128671,-0.927175
4,IGOV,iShares International Treasury Bond ETF,8.65%,9.56%,-0.71%,-3.32%,-0.86%,0.21%,"Apr 30, 2025","Jan 21, 2009",...,https://www.blackrock.com/us/individual/produc...,0.028,9.64,1.12,0.022,8.535,0.0854,-0.036838,0.095561,-0.827089
5,LQD,iShares iBoxx $ Investment Grade Corporate Bon...,2.22%,7.50%,2.61%,-0.17%,2.37%,4.41%,"Apr 30, 2025","Jul 22, 2002",...,https://www.blackrock.com/us/individual/produc...,0.054,12.87,1.11,0.044,9.740,0.0974,-0.005159,0.087919,-0.538662
6,LQDI,iShares Inflation Hedged Corporate Bond ETF,2.32%,6.38%,2.12%,4.01%,0,3.95%,"Apr 30, 2025","May 08, 2018",...,https://www.blackrock.com/us/individual/produc...,0.053,12.41,1.05,0.000,11.691,0.1169,0.036805,0.088434,-0.061007

### Step 11: Export Data to Excel

In [15]:
from openpyxl import load_workbook
from openpyxl.styles import Alignment, Font
import os

# Check if 'Ticker' is already the index or still a column
if 'Ticker' in bond_funds_sensitivity_df.columns:
    # Set 'Ticker' as index if it's still a column
    bond_funds_sensitivity_df.set_index('Ticker', inplace=True)
elif bond_funds_sensitivity_df.index.name != 'Ticker':
    # If it's neither a column nor the index name, print info for debugging
    print("Warning: 'Ticker' is not available as a column or index name.")
    print(f"Available columns: {bond_funds_sensitivity_df.columns.tolist()}")
    print(f"Current index name: {bond_funds_sensitivity_df.index.name}")

# Get the actual ticker symbol name for the best bond
if isinstance(best_bond_ticker, (int, np.integer)):
    best_bond_ticker_name = bond_funds_sensitivity_df.iloc[best_bond_ticker].name
    print(f"Converting best bond index {best_bond_ticker} to ticker name {best_bond_ticker_name}")
    best_bond_ticker = best_bond_ticker_name

# Write both DataFrames to Excel sheets
output_file = 'reports/portfolio.xlsx'

# First export the bond_funds_sensitivity_df
with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
    bond_funds_sensitivity_df.to_excel(
        writer, 
        sheet_name='Bond ETFs', 
        index=True, 
        startrow=0, 
        startcol=0
    )

# For the daily prices data, we need to merge with existing data
if os.path.exists(output_file):
    try:
        # Try to read existing data from the Daily Prices sheet
        existing_daily_prices = pd.read_excel(output_file, sheet_name='Daily Prices', index_col=0)
        
        # Ensure the index (Date) is in the right format for merging
        if isinstance(bonds_daily_filtered_df.index, pd.DatetimeIndex):
            existing_daily_prices.index = pd.to_datetime(existing_daily_prices.index)
        
        # Make sure best_bond_ticker is a valid column in bonds_daily_filtered_df
        if best_bond_ticker not in bonds_daily_filtered_df.columns:
            print(f"Warning: {best_bond_ticker} not found in columns. Available columns: {bonds_daily_filtered_df.columns.tolist()}")
        else:
            # Merge the DataFrames based on the Date index
            merged_daily_prices = pd.concat([existing_daily_prices, bonds_daily_filtered_df[best_bond_ticker]], axis=1)
            # Remove duplicate columns if any
            merged_daily_prices = merged_daily_prices.loc[:,~merged_daily_prices.columns.duplicated()]
            
            # Write the merged data back to Excel
            with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
                merged_daily_prices.to_excel(
                    writer,
                    sheet_name='Daily Prices',
                    index=True
                )
                
            print(f"Successfully merged daily price data with existing data in 'Daily Prices' sheet")
    
    except ValueError:  # Sheet doesn't exist yet
        # If the sheet doesn't exist, just write the data directly
        with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
            bonds_daily_filtered_df.to_excel(
                writer,
                sheet_name='Daily Prices',
                index=True
            )
        print(f"Created new 'Daily Prices' sheet with daily price data")
        
    # Now handle the monthly prices data
    try:
        # Try to read existing data from the Monthly Prices sheet
        existing_monthly_prices = pd.read_excel(output_file, sheet_name='Monthly Prices', index_col=0)
        
        # Ensure bonds_monthly_prices has a datetime index for merging
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
            
        if not isinstance(bonds_monthly_filtered_df.index, pd.DatetimeIndex):
            bonds_monthly_filtered_df.index = pd.to_datetime(bonds_monthly_filtered_df.index)
            
        # Ensure the existing data index is in datetime format
        if not isinstance(existing_monthly_prices.index, pd.DatetimeIndex):
            existing_monthly_prices.index = pd.to_datetime(existing_monthly_prices.index)
        
        # Make sure best_bond_ticker is a valid column in bonds_monthly_filtered_df
        if best_bond_ticker not in bonds_monthly_filtered_df.columns:
            print(f"Warning: {best_bond_ticker} not found in columns. Available columns: {bonds_monthly_filtered_df.columns.tolist()}")
        else:
            # Merge the DataFrames based on the Date index
            merged_monthly_prices = pd.concat([existing_monthly_prices, bonds_monthly_filtered_df[best_bond_ticker]], axis=1)
            # Remove duplicate columns if any
            merged_monthly_prices = merged_monthly_prices.loc[:,~merged_monthly_prices.columns.duplicated()]
            
            # Write the merged data back to Excel
            with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
                merged_monthly_prices.to_excel(
                    writer,
                    sheet_name='Monthly Prices',
                    index=True
                )
                
            print(f"Successfully merged monthly price data with existing data in 'Monthly Prices' sheet")
    
    except ValueError:  # Sheet doesn't exist yet
        # If the sheet doesn't exist, just write the data directly
        # Ensure bonds_monthly_prices has a proper index for Excel export
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
            
        with pd.ExcelWriter(output_file, mode='a', engine='openpyxl', if_sheet_exists='replace') as writer:
            bonds_monthly_filtered_df.to_excel(
                writer,
                sheet_name='Monthly Prices',
                index=True
            )
        print(f"Created new 'Monthly Prices' sheet with monthly price data")
else:
    # If the file doesn't exist yet, just write both daily and monthly data directly
    with pd.ExcelWriter(output_file, mode='w', engine='openpyxl') as writer:
        bonds_daily_filtered_df.to_excel(
            writer,
            sheet_name='Daily Prices',
            index=True
        )
        
        # Prepare monthly data for export
        if 'Date' in bonds_monthly_prices.columns:
            bonds_monthly_filtered_df = bonds_monthly_prices.set_index('Date')
        else:
            bonds_monthly_filtered_df = bonds_monthly_prices.copy()
        
        bonds_monthly_filtered_df.to_excel(
            writer,
            sheet_name='Monthly Prices',
            index=True
        )
    print(f"Created new portfolio.xlsx file with 'Daily Prices' and 'Monthly Prices' sheets")

display(bond_funds_sensitivity_df)

Converting best bond index 0 to ticker name TLT
Successfully merged daily price data with existing data in 'Daily Prices' sheet
Successfully merged monthly price data with existing data in 'Monthly Prices' sheet

,Name,YTD (%),1Y (%),3Y (%),5Y (%),10Y (%),Incept (%),Perf. as of,Inception Date,Net Assets,...,URL,Yield_To_Maturity,Weighted_Avg_Maturity,Convexity,Weighted_Avg_Coupon,Duration (D*),Price Change Sensitivity,Expected_Return,Standard_Deviation,Sharpe_Ratio
Ticker,,,,,,,,,,,,,,,,,,,,,
TLT,iShares 20+ Year Treasury Bond ETF,3.23%,5.46%,-6.03%,-9.43%,-0.87%,3.79%,"Apr 30, 2025","Jul 22, 2002",47129940736,...,https://www.blackrock.com/us/individual/produc...,0.049,25.73,3.41,0.029,18.131,0.1813,-0.106034,0.162693,-0.911122
ILTB,iShares Core 10+ Year USD Bond ETF,2.20%,6.73%,-1.03%,-3.92%,1.47%,3.87%,"Apr 30, 2025","Dec 08, 2009",599704097,...,https://www.blackrock.com/us/individual/produc...,0.056,21.92,2.35,0.040,14.881,0.1488,-0.046370,0.128154,-0.691117
IGLB,iShares 10+ Year Investment Grade Corporate Bo...,1.10%,6.19%,0.87%,-1.95%,2.09%,4.27%,"Apr 30, 2025","Dec 08, 2009",2474365039,...,https://www.blackrock.com/us/individual/produc...,0.060,22.13,2.17,0.046,14.583,0.1458,-0.026215,0.127023,-0.538599
TLH,iShares 10-20 Year Treasury Bond ETF,4.02%,7.73%,-2.63%,-6.71%,-0.35%,2.95%,"Apr 30, 2025","Jan 05, 2007",9952338249,...,https://www.blackrock.com/us/individual/produc...,0.048,17.12,1.89,0.032,13.185,0.1319,-0.077101,0.128671,-0.927175
IGOV,iShares International Treasury Bond ETF,8.65%,9.56%,-0.71%,-3.32%,-0.86%,0.21%,"Apr 30, 2025","Jan 21, 2009",992955881,...,https://www.blackrock.com/us/individual/produc...,0.028,9.64,1.12,0.022,8.535,0.0854,-0.036838,0.095561,-0.827089
LQD,iShares iBoxx $ Investment Grade Corporate Bon...,2.22%,7.50%,2.61%,-0.17%,2.37%,4.41%,"Apr 30, 2025","Jul 22, 2002",29316619618,...,https://www.blackrock.com/us/individual/produc...,0.054,12.87,1.11,0.044,9.740,0.0974,-0.005159,0.087919,-0.538662
LQDI,iShares Inflation Hedged Corporate Bond ETF,2.32%,6.38%,2.12%,4.01%,0,3.95%,"Apr 30, 2025","May 08, 2018",89759396,...,https://www.blackrock.com/us/individual/produc...,0.053,12.41,1.05,0.000,11.691,0.1169,0.036805,0.088434,-0.061007