# Portfolio Performance vs. Benchmark

### Step 1: Import Libraries

In [1]:
# Data manipulation libraries
import pandas as pd
import numpy as np
from scipy.optimize import minimize
from datetime import datetime, timedelta
from pandas.tseries.offsets import BDay

# Visualization libraries
import matplotlib.pyplot as plt
import plotly
import plotly.express as px
import seaborn as sns
import plotly.graph_objects as go
import plotly.io as pio
from IPython.display import Image, display

# System libraries
import os
import sys
import logging
import warnings

warnings.filterwarnings("ignore", category=UserWarning)  # Font warnings
warnings.filterwarnings("ignore", category=FutureWarning, message=".*inplace.*")  # Pandas warnings
logging.getLogger('matplotlib.font_manager').disabled = True

In [2]:
# UDFs
current_dir = os.path.abspath(os.path.join(os.getcwd(), '..', 'py')) 
sys.path.append(current_dir)
from quantstats_fix import *
from utils import load_and_filter_data, export_to_excel
qs.extend_pandas()

============================================================
               QuantStats Compatibility Tool
============================================================

Part 1: Directly patching QuantStats package files
------------------------------------------------------------
Found QuantStats utils file at: /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/__init__.py
Creating backup at: /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/__init__.py.bak
Successfully fixed indentation in QuantStats __init__.py file
✓ QuantStats utils file patched successfully

Part 2: Fixing resampling issues
------------------------------------------------------------
Found 1 potential QuantStats installation(s)
Checking /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py
✓ Found 'plot_timeseries' function in /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py
✓ No 'sum(axis=0)' calls found - may already be fixed
Examining /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py...
✓ Found 'plot_timeseries' function in /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py
✓ No 'sum(axis=0)' calls found - may already be fixed
No applicable fixes found for /opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py
⚠️ Resampling fix not applied or not needed

Part 3: Importing and patching QuantStats
------------------------------------------------------------
✓ Successfully imported quantstats
Successfully patched QuantStats HTML report functionality
✓ HTML report functionality enhanced with download button

### Step 2: Define Parameters

#### Dates

In [3]:
# Define the date range
end_date = (datetime.today() - BDay(1)).to_pydatetime()  # Subtract 1 business day
# end_date = pd.to_datetime('2025-04-26')  # Report date
start_date = end_date - timedelta(days=5*365)

# Convert datetime objects to Unix timestamps (seconds since Jan 1, 1970)
start_timestamp = int(start_date.timestamp())
end_timestamp = int(end_date.timestamp())

# Print the date range
days_difference = (end_date - start_date).days
print(f"Date Range: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}")
print(f"Time span: {days_difference} days ({days_difference/365:.2f} years)")

Date Range: 2020-07-05 to 2025-07-04
Time span: 1825 days (5.00 years)

#### Report File

In [4]:
output_file = f'portfolio-{datetime.date(end_date)}.xlsx'

# benchmark = 'ADME'
benchmark = pd.read_excel(output_file, sheet_name="benchmark")['Benchmark'].values[0]
print(benchmark)

AOR

#### Risk-free rate (T-bill, %)

In [5]:
# Load and process data
risk_free_df = pd.read_excel(output_file, sheet_name="daily_quotes", index_col=0)['^IRX']
# risk_free_rate  = 0.0433                              # 3‑month T‑Bill
risk_free_rate = risk_free_df.iloc[-1] / 100 

# Display result
print("Risk-Free Rate:", risk_free_rate, "-- 13 WEEK TREASURY BILL (^IRX)")

Risk-Free Rate: 0.0424 -- 13 WEEK TREASURY BILL (^IRX)

### Step 3: Read Portfolio Data (Excel)

In [6]:
portfolio_df = pd.read_excel(output_file, sheet_name="equity")

# Convert percentage strings to float values
portfolio_df['Weight'] = portfolio_df['Weight'].replace('%', '', regex=True).astype(float)
portfolio_tickers = portfolio_df["Ticker"].tolist()

print(portfolio_tickers)
display(portfolio_df)

['PGR', 'DE', 'XOM', 'SO', 'TJX', 'PG', 'UBER', 'TMUS', 'GILD']

,Ticker,Date,Name,Sector,Industry,Country,Website,Market Cap,Enterprise Value,Float Shares,...,52W High,52W Low,50 Day Avg,200 Day Avg,Short Ratio,Short % of Float,Weight,Expected Return,Standard Deviation,Sharpe Ratio
0,PGR,2025-07-07,The Progressive Corporation,Financial Services,Insurance - Property & Casualty,United States,https://www.progressive.com,153391366144,160543637504,584042891,...,292.99,207.50,274.32,261.98,2.09,0.01,0.347570,0.256104,0.248471,1.030721
1,DE,2025-07-07,Deere & Company,Industrials,Farm & Heavy Construction Machinery,United States,https://www.deere.com/en,141092732928,198049841152,270233944,...,533.78,340.20,503.09,457.07,2.98,0.01,0.158567,0.229470,0.290957,0.788676
2,XOM,2025-07-07,Exxon Mobil Corporation,Energy,Oil & Gas Integrated,United States,https://corporate.exxonmobil.com,483541614592,492180078592,4300373098,...,126.34,97.80,107.24,111.75,2.33,0.01,0.139829,0.207675,0.293716,0.707061
3,SO,2025-07-07,The Southern Company,Utilities,Utilities - Regulated Electric,United States,https://www.southerncompany.com,100678385664,172103221248,1095713937,...,94.45,77.62,89.84,88.19,3.68,0.02,0.097821,0.139234,0.190808,0.729706
4,TJX,2025-07-07,"The TJX Companies, Inc.",Consumer Cyclical,Apparel Retail,United States,https://www.tjx.com,140411928576,146574376960,1113373237,...,135.85,107.71,127.24,122.30,2.39,0.01,0.056213,0.170780,0.249358,0.684881
5,PG,2025-07-07,The Procter & Gamble Company,Consumer Defensive,Household & Personal Products,United States,https://www.pginvestor.com,377072353280,399611428864,2341001776,...,180.43,156.58,162.14,167.32,2.06,0.01,0.050000,0.068247,0.171670,0.397547
6,UBER,2025-07-07,"Uber Technologies, Inc.",Technology,Software - Application,United States,https://www.uber.com,195796238336,201133981696,2079708497,...,94.38,54.84,86.21,75.49,1.68,0.02,0.050000,0.106926,0.472239,0.226422
7,TMUS,2025-07-07,"T-Mobile US, Inc.",Communication Services,Telecom Services,United States,https://www.t-mobile.com,273366384640,380220145664,418139015,...,276.49,173.74,239.63,237.14,3.47,0.03,0.050000,0.148763,0.240472,0.618628
8,GILD,2025-07-07,"Gilead Sciences, Inc.",Healthcare,Drug Manufacturers - General,United States,https://www.gilead.com,139009179648,154071416832,1241354188,...,119.96,66.34,106.80,99.03,2.85,0.02,0.050000,0.091684,0.230571,0.397638

### Step 4: Download Returns

In [7]:
# stock_returns = qs.utils.download_returns(ticker=portfolio_tickers, period="5y").dropna()
stock_quotes = load_and_filter_data('../data/datasets/daily_stock_quotes.csv', portfolio_tickers, start_date, end_date)
stock_returns = np.log(stock_quotes / stock_quotes.shift(1)).dropna()

benchmark_quotes = load_and_filter_data('../data/datasets/daily_benchmark_quotes.csv', benchmark, start_date, end_date)
benchmark_returns = np.log(benchmark_quotes / benchmark_quotes.shift(1)).dropna()

# Display summary statistics for all assets
print("\nSharpe Ratios for individual assets:")
sharpes = {col: qs.stats.sharpe(stock_returns[col]) for col in stock_returns.columns}
for ticker, sharpe in sharpes.items():
    print(f"{ticker}: {sharpe:.4f}")

display(stock_returns.head())

Found 9 of 9 tickers in ../data/datasets/daily_stock_quotes.csv
Missing tickers: []
Found 1 of 1 tickers in ../data/datasets/daily_benchmark_quotes.csv
Missing tickers: []

Sharpe Ratios for individual assets:
DE: 0.8562
GILD: 0.4953
PG: 0.4708
PGR: 1.0434
SO: 0.7788
TJX: 0.7567
TMUS: 0.6975
UBER: 0.4496
XOM: 0.7892

,DE,GILD,PG,PGR,SO,TJX,TMUS,UBER,XOM
Date,,,,,,,,,
2020-07-07,-0.009536,-0.004435,0.004824,-0.017809,0.002059,-0.035600,-0.009236,0.009183,-0.026355
2020-07-08,-0.002012,-0.010692,0.005445,-0.008383,0.006380,0.001263,0.007703,0.033261,-0.002325
2020-07-09,-0.004644,-0.011943,-0.003319,0.005407,-0.021348,-0.017407,-0.004229,-0.023257,-0.041889
2020-07-10,0.009132,0.021365,0.011477,0.037462,0.024523,0.021397,0.008345,-0.000302,0.030477
2020-07-13,0.029375,0.004757,0.001277,-0.005208,-0.000906,-0.013718,-0.023974,-0.043794,0.000294

### Step 5: Plot Return Comparisons

In [8]:
# Calculate portfolio returns using weights from Excel file
portfolio_weights = portfolio_df.set_index('Ticker')['Weight'].to_dict()
weighted_returns = pd.DataFrame()

print("\nPortfolio Weights:")
for ticker in portfolio_tickers:
    weight = portfolio_weights.get(ticker, 0)
    print(f"{ticker}: {weight:.2%}")
    if ticker in stock_returns.columns:
        weighted_returns[ticker] = stock_returns[ticker] * weight

# Sum across all weighted returns to get the portfolio return
portfolio_return = weighted_returns.sum(axis=1)

# Create equal-weight portfolio for comparison
equal_weight = 1/len([t for t in portfolio_tickers if t in stock_returns.columns])
equal_weighted_returns = pd.DataFrame()

for ticker in portfolio_tickers:
    if ticker in stock_returns.columns:
        equal_weighted_returns[ticker] = stock_returns[ticker] * equal_weight
        
equal_weight_return = equal_weighted_returns.sum(axis=1)

print("\nPortfolio Performance Summary:")
print(f"Sharpe Ratio (Weighted Portfolio): {qs.stats.sharpe(portfolio_return):.4f}")
print(f"Sharpe Ratio (Equal-Weight): {qs.stats.sharpe(equal_weight_return):.4f}")

plt.figure(figsize=(12, 6))
(1 + portfolio_return).cumprod().plot(label='Weighted Portfolio')
(1 + equal_weight_return).cumprod().plot(label='Equal Weight')
(1 + benchmark_returns).cumprod().plot(label=benchmark)
plt.legend()
plt.title('Performance Comparison')
plt.ylabel('Cumulative Return')
plt.grid(True)
plt.show()

Portfolio Weights:
PGR: 34.76%
DE: 15.86%
XOM: 13.98%
SO: 9.78%
TJX: 5.62%
PG: 5.00%
UBER: 5.00%
TMUS: 5.00%
GILD: 5.00%

Portfolio Performance Summary:
Sharpe Ratio (Weighted Portfolio): 1.3583
Sharpe Ratio (Equal-Weight): 1.2421

### Step 6: Generate Reports

#### Portfolio (Weighted) vs Benchmark

In [9]:
portfolio_return = portfolio_return.resample('D').sum()  # Example of valid aggregation
portfolio_return.name = "Weighted Portfolio"

# Generate Report
qs.reports.html(
    portfolio_return,
    benchmark_returns,
    rf=risk_free_rate,
    figsize=(8, 5),
    # output=f'portfolio_vs_{benchmark}.html',
    output=f'portfolio_vs_benchmark-{datetime.date(end_date)}.html',
    title=f'Portfolio vs {benchmark} (Benchmark)',
    benchmark_title=f'{benchmark}',
    download_filename=f'portfolio_vs_{benchmark}.html'
)

qs.reports.full(
    portfolio_return, 
    benchmark_returns,
    rf=risk_free_rate, 
    figsize=(8, 5), 
    title=f'Portfolio vs {benchmark}',
    benchmark_title=f'{benchmark}')

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

Added download button and removed QuantStats attribution from portfolio_vs_benchmark-2025-07-04.html

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()

                           AOR         Strategy
-------------------------  ----------  ----------
Start Period               2020-07-08  2020-07-08
End Period                 2025-07-03  2025-07-03
Risk-Free Rate             4.24%       4.24%
Time in Market             68.0%       69.0%

Cumulative Return          41.83%      178.75%
CAGR﹪                     4.95%       15.24%

Sharpe                     0.12        0.83
Prob. Sharpe Ratio         40.98%      89.21%
Smart Sharpe               0.12        0.82
Sortino                    0.17        1.2
Smart Sortino              0.17        1.19
Sortino/√2                 0.12        0.85
Smart Sortino/√2           0.12        0.84
Omega                      1.18        1.18

Max Drawdown               -22.42%     -11.89%
Longest DD Days            869         232
Volatility (ann.)          8.89%       13.2%
R^2                        0.23        0.23
Information Ratio          0.05        0.05
Calmar                     0.22        1.28
Skew                       0.03        -0.34
Kurtosis                   6.91        6.56

Expected Daily %           0.02%       0.06%
Expected Monthly %         0.57%       1.69%
Expected Yearly %          6.0%        18.63%
Kelly Criterion            5.85%       9.62%
Risk of Ruin               0.0%        0.0%
Daily Value-at-Risk        -0.9%       -1.31%
Expected Shortfall (cVaR)  -0.9%       -1.31%

Max Consecutive Wins       5           5
Max Consecutive Losses     5           5
Gain/Pain Ratio            0.13        0.26
Gain/Pain (1M)             0.63        1.83

Payoff Ratio               0.95        0.99
Profit Factor              1.13        1.26
Common Sense Ratio         1.11        1.45
CPC Index                  0.58        0.69
Tail Ratio                 0.98        1.14
Outlier Win Ratio          7.37        4.69
Outlier Loss Ratio         3.84        2.72

MTD                        -0.21%      0.48%
3M                         6.03%       -1.65%
6M                         7.43%       12.64%
YTD                        7.21%       12.67%
1Y                         11.04%      23.56%
3Y (ann.)                  6.44%       14.88%
5Y (ann.)                  4.61%       14.46%
10Y (ann.)                 4.95%       15.24%
All-time (ann.)            4.95%       15.24%

Best Day                   4.67%       4.73%
Worst Day                  -3.36%      -7.23%
Best Month                 6.82%       12.6%
Worst Month                -7.2%       -9.13%
Best Year                  13.59%      25.93%
Worst Year                 -15.96%     11.22%

Avg. Drawdown              -1.48%      -2.28%
Avg. Drawdown Days         26          17
Recovery Factor            1.69        9.15
Ulcer Index                0.08        0.04
Serenity Index             0.15        3.0

Avg. Up Month              2.75%       4.5%
Avg. Down Month            -3.1%       -3.41%
Win Days %                 54.09%      54.94%
Win Month %                63.93%      65.57%
Win Quarter %              66.67%      71.43%
Win Year %                 83.33%      100.0%

Beta                       -           0.71
Alpha                      -           0.11
Correlation                -           47.72%
Treynor Ratio              -           246.36%

None

        Start      Valley         End  Days  Max Drawdown  99% Max Drawdown
1  2022-04-21  2022-06-17  2022-08-11   113    -11.889823        -11.585718
2  2022-09-13  2022-09-30  2022-10-27    45    -10.920484         -9.922427
3  2024-12-02  2025-01-10  2025-02-17    78    -10.017731         -9.452142
4  2025-04-02  2025-04-08  2025-05-15    44     -9.889612         -9.690553
5  2021-05-17  2021-09-20  2022-01-03   232     -9.687935         -9.439114

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

#### Portfolio (Weighted) vs Portolio (Equally-Weighted)

In [10]:
# Ensure equal_weight_return and portfolio_return are properly aggregated if resampled
equal_weight_return = equal_weight_return.resample('D').sum() if equal_weight_return.index.freq is None else equal_weight_return
portfolio_return = portfolio_return.resample('D').sum() if portfolio_return.index.freq is None else portfolio_return

# Set the name for the equal weight portfolio
equal_weight_return.name = "Equal Weight Portfolio"

# Generate Report
qs.reports.html(
    portfolio_return,
    equal_weight_return,
    rf=risk_free_rate,
    figsize=(8, 5),
    output=f'portfolio_vs_equal_weight-{datetime.date(end_date)}.html',
    title='Portfolio (Weighted) vs Portolio (Equally-Weighted)',
    benchmark_title="Equal Weight Portfolio",
    download_filename="portfolio_vs_equal_weight.html" 
)

qs.reports.full(
    portfolio_return, 
    equal_weight_return,
    rf=risk_free_rate, 
    figsize=(8, 5), 
    title='Portfolio vs Equal Weight',
    benchmark_title="Equal Weight Portfolio",
    )

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

Added download button and removed QuantStats attribution from portfolio_vs_equal_weight-2025-07-04.html

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()

                           Equal Weight Portfolio    Strategy
-------------------------  ------------------------  ----------
Start Period               2020-07-07                2020-07-07
End Period                 2025-07-03                2025-07-03
Risk-Free Rate             4.24%                     4.24%
Time in Market             69.0%                     69.0%

Cumulative Return          136.25%                   175.08%
CAGR﹪                     12.63%                    15.02%

Sharpe                     0.69                      0.81
Prob. Sharpe Ratio         82.91%                    88.47%
Smart Sharpe               0.68                      0.8
Sortino                    1.01                      1.18
Smart Sortino              0.99                      1.16
Sortino/√2                 0.71                      0.83
Smart Sortino/√2           0.7                       0.82
Omega                      1.18                      1.18

Max Drawdown               -15.12%                   -11.89%
Longest DD Days            231                       232
Volatility (ann.)          12.28%                    13.2%
R^2                        0.83                      0.83
Information Ratio          0.03                      0.03
Calmar                     0.84                      1.26
Skew                       -0.2                      -0.34
Kurtosis                   5.48                      6.54

Expected Daily %           0.05%                     0.06%
Expected Monthly %         1.42%                     1.67%
Expected Yearly %          15.41%                    18.37%
Kelly Criterion            9.46%                     10.46%
Risk of Ruin               0.0%                      0.0%
Daily Value-at-Risk        -1.22%                    -1.31%
Expected Shortfall (cVaR)  -1.22%                    -1.31%

Max Consecutive Wins       5                         5
Max Consecutive Losses     5                         5
Gain/Pain Ratio            0.23                      0.26
Gain/Pain (1M)             1.66                      1.81

Payoff Ratio               1.0                       1.01
Profit Factor              1.23                      1.26
Common Sense Ratio         1.4                       1.43
CPC Index                  0.67                      0.7
Tail Ratio                 1.13                      1.14
Outlier Win Ratio          6.11                      5.66
Outlier Loss Ratio         3.21                      3.03

MTD                        1.02%                     0.48%
3M                         0.36%                     -1.65%
6M                         13.71%                    12.64%
YTD                        13.88%                    12.67%
1Y                         24.39%                    23.56%
3Y (ann.)                  14.26%                    14.88%
5Y (ann.)                  12.64%                    14.46%
10Y (ann.)                 12.63%                    15.02%
All-time (ann.)            12.63%                    15.02%

Best Day                   4.73%                     4.73%
Worst Day                  -6.02%                    -7.23%
Best Month                 13.98%                    12.6%
Worst Month                -8.23%                    -9.13%
Best Year                  20.43%                    25.93%
Worst Year                 10.42%                    11.22%

Avg. Drawdown              -2.23%                    -2.28%
Avg. Drawdown Days         18                        17
Recovery Factor            6.05                      9.04
Ulcer Index                0.04                      0.04
Serenity Index             2.57                      2.97

Avg. Up Month              3.88%                     4.36%
Avg. Down Month            -2.92%                    -3.04%
Win Days %                 54.82%                    54.9%
Win Month %                65.57%                    65.57%
Win Quarter %              80.95%                    71.43%
Win Year %                 100.0%                    100.0%

Beta                       -                         0.98
Alpha                      -                         0.02
Correlation                -                         91.01%
Treynor Ratio              -                         174.54%

None

        Start      Valley         End  Days  Max Drawdown  99% Max Drawdown
1  2022-04-21  2022-06-17  2022-08-11   113    -11.889823        -11.585718
2  2022-09-13  2022-09-30  2022-10-27    45    -10.920484         -9.922427
3  2024-12-02  2025-01-10  2025-02-17    78    -10.017731         -9.452142
4  2025-04-02  2025-04-08  2025-05-15    44     -9.889612         -9.690553
5  2021-05-17  2021-09-20  2022-01-03   232     -9.687935         -9.439114

/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)