# Portfolio Performance vs. Benchmark

## Import Libraries

In [1]:
from datetime import datetime, timedelta
import os
import sys
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import logging
import warnings

# Suppress warnings
warnings.filterwarnings("ignore", category=UserWarning)  # Font warnings
warnings.filterwarnings("ignore", category=FutureWarning, message=".*inplace.*")  # Pandas warnings
logging.getLogger('matplotlib.font_manager').disabled = True

In [2]:
current_dir = os.path.abspath(os.path.join(os.getcwd(), '..', 'py')) 
sys.path.append(current_dir)
from quantstats_fix import *
qs.extend_pandas()

============================================================
               QuantStats Compatibility Tool
============================================================

Part 1: Directly patching QuantStats package files
------------------------------------------------------------
Found QuantStats utils file at: /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/__init__.py
Successfully fixed indentation in QuantStats __init__.py file
✓ QuantStats utils file patched successfully

Part 2: Fixing resampling issues
------------------------------------------------------------
Found 1 potential QuantStats installation(s)
Checking /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py
✓ Found 'plot_timeseries' function in /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py
✓ No 'sum(axis=0)' calls found - may already be fixed
Examining /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py...
✓ Found 'plot_timeseries' function in /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py
✓ No 'sum(axis=0)' calls found - may already be fixed
No applicable fixes found for /home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py
⚠️ Resampling fix not applied or not needed

Part 3: Importing and patching QuantStats
------------------------------------------------------------
✓ Successfully imported quantstats
Successfully patched QuantStats HTML report functionality
✓ HTML report functionality enhanced with download button

### Step 1: Define Parameters

In [3]:
from datetime import datetime, timedelta
from pandas.tseries.offsets import BDay

# Time Range
end_date = (datetime.today() - BDay(1)).to_pydatetime()  # Subtract 1 business day
start_date = end_date - timedelta(days=5*365)

# Convert datetime objects to Unix timestamps (seconds since Jan 1, 1970)
start_timestamp = int(start_date.timestamp())
end_timestamp = int(end_date.timestamp())

# Write both DataFrames to Excel sheets
output_file = f'portfolio-{datetime.date(end_date)}.xlsx'

In [4]:
# benchmark = 'ADME'
benchmark = pd.read_excel(output_file, sheet_name="benchmark")['Benchmark'].values[0]
print(benchmark)

QUAL

In [5]:
# Load and process data
risk_free_df = pd.read_excel(output_file, sheet_name="daily_quotes", index_col=0)['^IRX']
# risk_free_rate  = 0.0433                              # 3‑month T‑Bill
risk_free_rate = risk_free_df.iloc[-1] / 100 

# Display result
print("Risk-Free Rate:", risk_free_rate, "-- 13 WEEK TREASURY BILL (^IRX)")

Risk-Free Rate: 0.042800000000000005 -- 13 WEEK TREASURY BILL (^IRX)

### Step 2: Read Portfolio Data (Excel)

In [6]:
portfolio_df = pd.read_excel(output_file, sheet_name="equity")

# Convert percentage strings to float values
portfolio_df['Weight'] = portfolio_df['Weight'].replace('%', '', regex=True).astype(float)
portfolio_tickers = portfolio_df["Ticker"].tolist()

print(portfolio_tickers)
display(portfolio_df)

['PGR', 'GE', 'WMT', 'TJX', 'LIN']

,Ticker,Date,Name,Sector,Industry,Country,Website,Market Cap,Enterprise Value,Float Shares,...,52W High,52W Low,50 Day Avg,200 Day Avg,Short Ratio,Short % of Float,Weight,Expected Return,Standard Deviation,Sharpe Ratio
0,PGR,2025-05-13,The Progressive Corporation,Financial Services,Insurance - Property & Casualty,United States,https://www.progressive.com,165661032448,169764945920,584001855,...,292.99,201.34,276.14,254.98,1.70,0.01,0.362159,0.292428,0.250981,1.165141
1,GE,2025-05-13,GE Aerospace,Industrials,Aerospace & Defense,United States,https://www.geaerospace.com,236290703360,237156466688,1062600970,...,223.54,150.20,196.84,184.73,1.56,0.01,0.307731,0.425319,0.348210,1.221443
2,WMT,2025-05-13,Walmart Inc.,Consumer Defensive,Discount Stores,United States,https://corporate.walmart.com,767125291008,835385163776,4349220992,...,105.30,59.44,91.17,87.01,1.95,0.01,0.226262,0.177300,0.211151,0.839682
3,TJX,2025-05-13,"The TJX Companies, Inc.",Consumer Cyclical,Apparel Retail,United States,https://www.tjx.com,146059231232,153582092288,1114419446,...,132.47,97.53,123.10,120.10,2.14,0.01,0.053848,0.217260,0.257557,0.843543
4,LIN,2025-05-13,Linde plc,Basic Materials,Specialty Chemicals,United Kingdom,https://www.linde.com,212141195264,234199515136,469592833,...,487.49,408.65,453.48,454.60,1.99,0.01,0.050000,0.192355,0.224857,0.855455

### Step 3: Download Returns

In [7]:
# stock_returns = qs.utils.download_returns(ticker=portfolio_tickers, period="5y").dropna()
stock_quotes = pd.read_csv('../data/datasets/daily_stock_quotes.csv', index_col=0)[portfolio_tickers]
stock_quotes.index = pd.to_datetime(stock_quotes.index)  # Add this line
stock_returns = np.log(stock_quotes / stock_quotes.shift(1)).dropna()

benchmark_quotes = pd.read_csv('../data/datasets/daily_benchmark_quotes.csv', index_col=0)[benchmark]
benchmark_quotes.index = pd.to_datetime(benchmark_quotes.index)  # Add this line
benchmark_returns = np.log(benchmark_quotes / benchmark_quotes.shift(1)).dropna()

# Display summary statistics for all assets
print("\nSharpe Ratios for individual assets:")
sharpes = {col: qs.stats.sharpe(stock_returns[col]) for col in stock_returns.columns}
for ticker, sharpe in sharpes.items():
    print(f"{ticker}: {sharpe:.4f}")

display(stock_returns.head())

Sharpe Ratios for individual assets:
PGR: 1.1533
GE: 1.1408
WMT: 0.8764
TJX: 0.8241
LIN: 0.8550

                 PGR        GE       WMT       TJX       LIN
Date
2020-05-12 -0.013382 -0.031363  0.000779 -0.050690 -0.020376
2020-05-13  0.007777 -0.035569 -0.000519 -0.042923 -0.023859
2020-05-14  0.013429 -0.015743 -0.002341  0.015866  0.002639
2020-05-15  0.033022 -0.037477  0.020364  0.052949  0.018459
2020-05-18  0.005351  0.133016  0.013433  0.053508  0.051576

### Step 4: Plot Return Comparisons

In [8]:
# Calculate portfolio returns using weights from Excel file
portfolio_weights = portfolio_df.set_index('Ticker')['Weight'].to_dict()
weighted_returns = pd.DataFrame()

print("\nPortfolio Weights:")
for ticker in portfolio_tickers:
    weight = portfolio_weights.get(ticker, 0)
    print(f"{ticker}: {weight:.2%}")
    if ticker in stock_returns.columns:
        weighted_returns[ticker] = stock_returns[ticker] * weight

# Sum across all weighted returns to get the portfolio return
portfolio_return = weighted_returns.sum(axis=1)

# Create equal-weight portfolio for comparison
equal_weight = 1/len([t for t in portfolio_tickers if t in stock_returns.columns])
equal_weighted_returns = pd.DataFrame()

for ticker in portfolio_tickers:
    if ticker in stock_returns.columns:
        equal_weighted_returns[ticker] = stock_returns[ticker] * equal_weight
        
equal_weight_return = equal_weighted_returns.sum(axis=1)

print("\nPortfolio Performance Summary:")
print(f"Sharpe Ratio (Weighted Portfolio): {qs.stats.sharpe(portfolio_return):.4f}")
print(f"Sharpe Ratio (Equal-Weight): {qs.stats.sharpe(equal_weight_return):.4f}")
print(f"Sharpe Ratio (Benchmark {benchmark}): {qs.stats.sharpe(benchmark_returns):.4f}")

plt.figure(figsize=(12, 6))
(1 + portfolio_return).cumprod().plot(label='Weighted Portfolio')
(1 + equal_weight_return).cumprod().plot(label='Equal Weight')
(1 + benchmark_returns).cumprod().plot(label=benchmark)
plt.legend()
plt.title('Performance Comparison')
plt.ylabel('Cumulative Return')
plt.grid(True)
plt.show()

Portfolio Weights:
PGR: 36.22%
GE: 30.77%
WMT: 22.63%
TJX: 5.38%
LIN: 5.00%

Portfolio Performance Summary:
Sharpe Ratio (Weighted Portfolio): 1.5517
Sharpe Ratio (Equal-Weight): 1.4673
Sharpe Ratio (Benchmark QUAL): 0.7839

### Step 5: Generate Reports

#### Portfolio (Weighted) vs Benchmark

In [9]:
portfolio_return = portfolio_return.resample('D').sum()  # Example of valid aggregation
portfolio_return.name = "Weighted Portfolio"

# Generate Report
qs.reports.html(
    portfolio_return,
    benchmark_returns,
    rf=risk_free_rate,
    figsize=(8, 5),
    # output=f'portfolio_vs_{benchmark}.html',
    output=f'portfolio_vs_benchmark-{datetime.date(end_date)}.html',
    title=f'Portfolio vs {benchmark} (Benchmark)',
    benchmark_title=f'{benchmark}',
    download_filename=f'portfolio_vs_{benchmark}.html'
)

qs.reports.full(
    portfolio_return, 
    benchmark_returns,
    rf=risk_free_rate, 
    figsize=(8, 5), 
    title=f'Portfolio vs {benchmark}',
    benchmark_title=f'{benchmark}')

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

Added download button and removed QuantStats attribution from portfolio_vs_benchmark-2025-05-12.html

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()

                           QUAL        Strategy
-------------------------  ----------  ----------
Start Period               2020-05-13  2020-05-13
End Period                 2025-05-12  2025-05-12
Risk-Free Rate             4.28%       4.28%
Time in Market             69.0%       69.0%

Cumulative Return          92.39%      296.38%
CAGR﹪                     9.46%       20.95%

Sharpe                     0.4         1.03
Prob. Sharpe Ratio         49.16%      95.01%
Smart Sharpe               0.39        1.03
Sortino                    0.56        1.52
Smart Sortino              0.56        1.51
Sortino/√2                 0.39        1.07
Smart Sortino/√2           0.39        1.07
Omega                      1.23        1.23

Max Drawdown               -30.09%     -18.95%
Longest DD Days            743         307
Volatility (ann.)          15.16%      15.52%
R^2                        0.29        0.29
Information Ratio          0.04        0.04
Calmar                     0.31        1.11
Skew                       -0.13       -0.33
Kurtosis                   7.88        8.19

Expected Daily %           0.04%       0.08%
Expected Monthly %         1.08%       2.28%
Expected Yearly %          11.52%      25.8%
Kelly Criterion            3.21%       11.07%
Risk of Ruin               0.0%        0.0%
Daily Value-at-Risk        -1.53%      -1.53%
Expected Shortfall (cVaR)  -1.53%      -1.53%

Max Consecutive Wins       5           5
Max Consecutive Losses     5           5
Gain/Pain Ratio            0.15        0.31
Gain/Pain (1M)             0.8         2.12

Payoff Ratio               0.96        1.03
Profit Factor              1.15        1.31
Common Sense Ratio         1.25        1.48
CPC Index                  0.58        0.74
Tail Ratio                 1.08        1.13
Outlier Win Ratio          5.73        5.24
Outlier Loss Ratio         3.19        3.09

MTD                        4.04%       2.38%
3M                         -5.17%      2.52%
6M                         -4.96%      11.92%
YTD                        -1.87%      17.46%
1Y                         7.61%       35.09%
3Y (ann.)                  11.21%      28.41%
5Y (ann.)                  9.05%       20.26%
10Y (ann.)                 9.46%       20.95%
All-time (ann.)            9.46%       20.95%

Best Day                   8.32%       7.13%
Worst Day                  -6.11%      -9.07%
Best Month                 9.76%       14.73%
Worst Month                -10.0%      -9.62%
Best Year                  29.06%      54.37%
Worst Year                 -23.31%     2.84%

Avg. Drawdown              -1.98%      -2.16%
Avg. Drawdown Days         19          15
Recovery Factor            2.45        7.73
Ulcer Index                0.11        0.05
Serenity Index             0.3         2.68

Avg. Up Month              4.78%       5.83%
Avg. Down Month            -5.07%      -4.8%
Win Days %                 52.64%      54.94%
Win Month %                60.66%      70.49%
Win Quarter %              66.67%      85.71%
Win Year %                 66.67%      100.0%

Beta                       -           0.55
Alpha                      -           0.15
Correlation                -           53.44%
Treynor Ratio              -           534.08%

None

        Start      Valley         End  Days  Max Drawdown  99% Max Drawdown
1  2022-01-18  2022-06-17  2022-11-20   307    -18.951594        -18.950397
2  2025-02-20  2025-04-07  2025-05-06    76    -13.920273        -13.684749
3  2020-06-09  2020-06-26  2020-08-27    80    -11.089830        -10.630402
4  2021-05-11  2021-12-01  2022-01-06   241     -9.454120         -8.302902
5  2021-01-13  2021-02-01  2021-03-14    61     -8.311823         -8.000274

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

#### Portfolio (Weighted) vs Portolio (Equally-Weighted)

In [10]:
# Ensure equal_weight_return and portfolio_return are properly aggregated if resampled
equal_weight_return = equal_weight_return.resample('D').sum() if equal_weight_return.index.freq is None else equal_weight_return
portfolio_return = portfolio_return.resample('D').sum() if portfolio_return.index.freq is None else portfolio_return

# Set the name for the equal weight portfolio
equal_weight_return.name = "Equal Weight Portfolio"

# Generate Report
qs.reports.html(
    portfolio_return,
    equal_weight_return,
    rf=risk_free_rate,
    figsize=(8, 5),
    output=f'portfolio_vs_equal_weight-{datetime.date(end_date)}.html',
    title='Portfolio (Weighted) vs Portolio (Equally-Weighted)',
    benchmark_title="Equal Weight Portfolio",
    download_filename="portfolio_vs_equal_weight.html" 
)

qs.reports.full(
    portfolio_return, 
    equal_weight_return,
    rf=risk_free_rate, 
    figsize=(8, 5), 
    title='Portfolio vs Equal Weight',
    benchmark_title="Equal Weight Portfolio",
    )

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)

Added download button and removed QuantStats attribution from portfolio_vs_equal_weight-2025-05-12.html

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.prod with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/stats.py:510: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns = _utils._prepare_returns(returns, rf).resample(resolution).sum()

                           Equal Weight Portfolio    Strategy
-------------------------  ------------------------  ----------
Start Period               2020-05-12                2020-05-12
End Period                 2025-05-12                2025-05-12
Risk-Free Rate             4.28%                     4.28%
Time in Market             69.0%                     69.0%

Cumulative Return          231.52%                   289.22%
CAGR﹪                     17.99%                    20.63%

Sharpe                     0.93                      1.02
Prob. Sharpe Ratio         92.4%                     94.52%
Smart Sharpe               0.93                      1.01
Sortino                    1.37                      1.49
Smart Sortino              1.37                      1.49
Sortino/√2                 0.97                      1.05
Smart Sortino/√2           0.97                      1.05
Omega                      1.23                      1.23

Max Drawdown               -19.82%                   -18.95%
Longest DD Days            309                       307
Volatility (ann.)          14.46%                    15.53%
R^2                        0.9                       0.9
Information Ratio          0.03                      0.03
Calmar                     0.91                      1.09
Skew                       -0.08                     -0.33
Kurtosis                   6.78                      8.16

Expected Daily %           0.07%                     0.07%
Expected Monthly %         1.98%                     2.25%
Expected Yearly %          22.11%                    25.42%
Kelly Criterion            11.44%                    11.63%
Risk of Ruin               0.0%                      0.0%
Daily Value-at-Risk        -1.43%                    -1.53%
Expected Shortfall (cVaR)  -1.43%                    -1.53%

Max Consecutive Wins       5                         5
Max Consecutive Losses     5                         5
Gain/Pain Ratio            0.28                      0.3
Gain/Pain (1M)             1.91                      2.09

Payoff Ratio               1.02                      1.04
Profit Factor              1.28                      1.3
Common Sense Ratio         1.49                      1.47
CPC Index                  0.72                      0.74
Tail Ratio                 1.16                      1.13
Outlier Win Ratio          5.7                       5.26
Outlier Loss Ratio         2.98                      2.83

MTD                        1.93%                     2.38%
3M                         1.64%                     2.52%
6M                         9.95%                     11.92%
YTD                        13.8%                     17.46%
1Y                         30.73%                    35.09%
3Y (ann.)                  23.86%                    28.41%
5Y (ann.)                  17.49%                    20.26%
10Y (ann.)                 17.99%                    20.63%
All-time (ann.)            17.99%                    20.63%

Best Day                   7.07%                     7.13%
Worst Day                  -7.29%                    -9.07%
Best Month                 15.59%                    14.73%
Worst Month                -10.4%                    -9.62%
Best Year                  41.33%                    54.37%
Worst Year                 0.44%                     2.84%

Avg. Drawdown              -2.27%                    -2.15%
Avg. Drawdown Days         16                        15
Recovery Factor            6.43                      7.64
Ulcer Index                0.05                      0.05
Serenity Index             1.99                      2.65

Avg. Up Month              4.71%                     5.15%
Avg. Down Month            -4.27%                    -4.47%
Win Days %                 55.29%                    54.89%
Win Month %                72.13%                    70.49%
Win Quarter %              80.95%                    85.71%
Win Year %                 100.0%                    100.0%

Beta                       -                         1.02
Alpha                      -                         0.02
Correlation                -                         94.88%
Treynor Ratio              -                         279.76%

None

        Start      Valley         End  Days  Max Drawdown  99% Max Drawdown
1  2022-01-18  2022-06-17  2022-11-20   307    -18.951594        -18.950397
2  2025-02-20  2025-04-07  2025-05-06    76    -13.920273        -13.684749
3  2020-06-09  2020-06-26  2020-08-27    80    -11.089830        -10.630402
4  2021-05-11  2021-12-01  2022-01-06   241     -9.454120         -8.302902
5  2021-01-13  2021-02-01  2021-03-14    61     -8.311823         -8.000274

/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:555: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:557: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  .resample("A")
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:565: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").apply(_stats.comp)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/wrappers.py:568: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  returns = returns.resample("A").last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:433: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:435: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  .resample(resample)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:440: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  returns.fillna(0).resample(resample).apply(apply_fnc).resample(resample).last()
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1018: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  port["Monthly"] = port["Daily"].resample("M").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1021: FutureWarning: 'Q' is deprecated and will be removed in a future version, please use 'QE' instead.
  port["Quarterly"] = port["Daily"].resample("Q").apply(apply_fnc)
/home/renanmogo/mfin-portfolio-management/.venv/lib/python3.13/site-packages/quantstats/_plotting/core.py:1024: FutureWarning: 'A' is deprecated and will be removed in a future version, please use 'YE' instead.
  port["Yearly"] = port["Daily"].resample("A").apply(apply_fnc)